### ISSUE TITLE
ui is all messed up after both webui and IB update, big ass button and refresh icon overflow to 2nd row, most stuffs on the right side are missing too :)) 

### ISSUE THREAD

**Issue by bryanray** [AlUlkesh/stable-diffusion-webui-images-browser#101]
[![Screenshot-2.png](https://i.postimg.cc/ZRfZpX2s/Screenshot-2.png)](https://postimg.cc/ft06hqwY)

ui is all messed up after both webui and IB update, big ass button and refresh icon overflow to 2nd row, most stuffs on the right side are missing too :))

**Comment by AlUlkesh** [comment]
Try a different browser, but yes, we'll have to wait here. See #100.

**Comment by bryanray** [comment]
these days all browsers are the same core no diff

you are right, gotta wait for webui updates
