### ISSUE TITLE
Image ribbon cuts off, Left and Right

### ISSUE THREAD

**Issue by Piscabo** [AlUlkesh/stable-diffusion-webui-images-browser#106]
Images below cannot be controlled or scrolled so you can see the first image on the left or the last on the right. Is it possible to make them scroll or wrap? A weird line at the bottom...
![image](https://user-images.githubusercontent.com/123719842/228631264-0500c6f4-0035-48d9-bcf2-fd7adc6c9b17.png)

**Comment by AlUlkesh** [comment]
That's the same symptom as something I just fixed yesterday. Are you running the latest commit on this extension?

**Comment by Piscabo** [comment]
I want to update but my extension suddenly shows unknown.
![image](https://user-images.githubusercontent.com/123719842/229201772-53695c9e-785d-42cd-85b5-c4d3b4f94d09.png)
Should I just git pull inside the extension... will it fix the link?

**Comment by AlUlkesh** [comment]
I suppose you didn't do a git checkout before?

If not, then yes, try git pull in the extension directory.
