### ISSUE TITLE
Generation Info does not get updated correctly when changing between images

### ISSUE THREAD

**Issue by erasels** [AlUlkesh/stable-diffusion-webui-images-browser#109]
This is likely related to #98 
I was on version a9032d4d32b6e005ba47ed8b5438b61337cb6330 and accidentally updated it today to the newest version df3d541307ff59e06a9de982be25c5f12d5b6d9c I assume.
![version](https://user-images.githubusercontent.com/20698806/228908568-71086ddf-fa49-4e03-9810-4c4115455ccf.png)

I use Windows 10 and am using the automatic1111 webui version from the 26th.

When switching between images the General info will be updated and within 0.5 seconds be overwritten by the old image information. When clicking send to txt2img the old information will then be sent.

Here is a screenshot showing the issue. Addition General info below the image shows the correct information while General info on the right does not:
![image of issue](https://user-images.githubusercontent.com/20698806/228907576-202d9339-216e-40af-8a8a-fcad7b23a843.png)

It does not always happen, however it is easily reproducible by switching between multiple images within 1-3 second intervals.

I tested reverting via git reset but the issue persists. The only other change in environment is that I tried out the Image Aesthetics Scorer extension but have since removed again.

**Comment by erasels** [comment]
Tried all the suggested fixes:
* Updated to the newest version
* Made changes to the java script files and restarted
* Couldn't find a user.css file but added the code to the style.css in the a1111 base dir.
* Tried opening it on Edge
None of these worked, the error persits and is unaffected.

**Comment by AlUlkesh** [comment]
Are you using the ranking feature? There's currently another issue and I wonder if this is related.

**Comment by erasels** [comment]
Oh, that might be it! Yes, I use the feature extensively, I'm a big fan of it.

On a small test I was unable to get the General info stuck when switching between unranked images. But when switching between images that are ranked I had a much higher rate of the tab getting stuck on old Information.

**Comment by AlUlkesh** [comment]
That would be good, if it's the same issue. Can you try the latest commit? More info is here: #108

**Comment by erasels** [comment]
Fixed! Thank you very much 😄
