### ISSUE TITLE
Seems conflict with State

### ISSUE THREAD

**Issue by SLAPaper** [AlUlkesh/stable-diffusion-webui-images-browser#110]
Corresponding issue of State: https://github.com/ilian6806/stable-diffusion-webui-state/issues/12

Enable state causing Image browser lose the ability to show full UI & show image metadata

Disable State:
![image](https://user-images.githubusercontent.com/7543632/228928099-10dd65b8-9efa-48dc-9c52-b5e6c2d45165.png)

Enable State:
![image](https://user-images.githubusercontent.com/7543632/228928299-3319f301-7db0-4573-b55e-94f22e759a68.png)

There is no relevant output in console.

**Comment by AlUlkesh** [comment]
Yes, we're both using a global javascript variable called "state". I'll change it on my end.

**Comment by SLAPaper** [comment]
> Can you check, if this commit solves the issue?

It works! thanks!
