### ISSUE TITLE
Request: Hide other generated images

### ISSUE THREAD

**Issue by Averytingwong** [AlUlkesh/stable-diffusion-webui-images-browser#111]
Hi, would love a function that would hide generated controlnet maps (like depth maps) from the main browser so only primary images are displayed. They're all stored in sub directories, but turning off subdirectories in image browser just disabled everything (my generations are organized into folders with dates). Thanks!

**Comment by AlUlkesh** [comment]
Any suggestion as to how I could recognize these?
