### ISSUE TITLE
got 2 'maintenance'  tabs on the ui,and cant get the PNG INFO.

### ISSUE THREAD

**Issue by kou201** [AlUlkesh/stable-diffusion-webui-images-browser#112]
![image](https://user-images.githubusercontent.com/55701610/228995285-af273dc5-509b-4518-be54-f75cdec38197.png)

![image](https://user-images.githubusercontent.com/55701610/228995381-77e5b295-fe1f-4456-8da7-2625161e380a.png)

I tried to turn it off in settings, but this would only leave one of the 'Maintenance' tabs left and cannot be closed directly.

![image](https://user-images.githubusercontent.com/55701610/228995839-ea149e80-7cb6-440b-ab4f-1bdfbf14734a.png)

![image](https://user-images.githubusercontent.com/55701610/228995664-90f98683-5ee0-484f-a401-09e625e6d264.png)

**Comment by thejohnd0e** [comment]
same issue

**Comment by AlUlkesh** [comment]
I'm not sure those two are related. To fix the double tab, go into Settings - Image Browser and remove the Maintenance entry:
![image](https://user-images.githubusercontent.com/99896447/229161501-8ae2275e-4906-4bc9-a5e4-b1d6a3a68622.png)

Then restart webui.

If the other issue still persists, please try this, if you haven't already: #107
