### ISSUE TITLE
Image deletion functionalities unavailable after thumbnails are being displayed

### ISSUE THREAD

**Issue by Harvester62** [AlUlkesh/stable-diffusion-webui-images-browser#114]
I am experiencing a strange behavior of this Extension. When switching to the Image Browser, at first the thumbnails view is empty and at the bottom the deletion button and other options are visible, but soon after the thumbnails are displayed these options disappear from the UI, being so unable to delete or batch delete generated images. This happens in all the tabs (txt2img, img2img, grids etc.).

Here follow two screenshots of the txt2img tab before and after thumbnails display:
![immagine](https://user-images.githubusercontent.com/29801031/229274455-77347b86-9e3f-4ed3-9889-18d781ee8672.png)

![immagine](https://user-images.githubusercontent.com/29801031/229274515-21dc4465-f4c3-4981-b488-e0e573b93797.png)

This is the error message in the console, but I am not sure it is related to this issue:

![immagine](https://user-images.githubusercontent.com/29801031/229274648-18629ea2-791e-4e50-95ce-130c8edf52de.png)

I am on Windows 10 Pro 64bit, 32GB RAM, Nvidia GTX1070 (8GB VRAM)
Browser: Firefox v111.0.1 (64 bit)
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Images Browser hash: 88388c78 (Fri Mar 31 15:27:56 2023)

**Comment by AlUlkesh** [comment]
You need to click on a thumbnail first, for the delete to become available. Does that not work?

**Comment by Harvester62** [comment]
Not sure why it didn't work before, but now it seems to be working properly again. Let's close this bug report and thank you. Regards.

**Comment by AlUlkesh** [comment]
Ah, good to hear.

**Comment by Harvester62** [comment]
I am still having this problem with the txt2img-grids tab but I will see if it will go away as for the other tabs.

**Comment by AlUlkesh** [comment]
Do you have the latest version of the extension? There was a fix that solved a grids issue yesterday.

**Comment by Harvester62** [comment]
I always update both SD Web UI and all Scripts and Extensions, almost daily, I added the hash of the extension for your reference. I updated again everything (Images Browser's hash is now db40a6e9 (Sat Apr 1 13:48:20 2023)) and opened the Web UI inside another browser, Brave, just in case, and now both img2img and txt2img-grid tab do not display the delete functions at the bottom. This is the error message I get in the console:

Task exception was never retrieved
future: <Task finished name='jp9uqf0ylmq_2238' coro=<Queue.process_events() done, defined at C:\stable-diffusion-webui\venv\lib\site-packages\gradio\queueing.py:343> exception=ValidationError(model='PredictBody', errors=[{'loc': ('data',), 'msg': 'field required', 'type': 'value_error.missing'}])>
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "pydantic\main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PredictBody
data
  field required (type=value_error.missing)

Then I opened also the Web UI in the Firefox Browser, and there the txt2img-grid still didn't show the delete functions but the img2img yes, and after a few retries and refreshes of the thumbnails this error was added in the console:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Connessione in corso interrotta forzatamente dall'host remoto

I am a little confused, not sure if the problem is in the extension or in the Web UI server.

**Comment by AlUlkesh** [comment]
I agree, confusing, I also don't know where this error comes from. Almost seems like something got messed up. You could try and delete the venv directory, then it will be recreated the next time you start webui-user.

Or to be really sure you could install a new version of webui in a new directory and then also only this extension and see if this issue persists.

**Comment by Harvester62** [comment]
Considering the huge amount of Extensions I have to keep installed for translation purposes (more than 80), I can probably try the second option you suggested, so to test only Images Browser. I will let you know, currently I am trying to solve a huge mess with the localization.json file non longer in sync with my localization version (almost 8K lines of items to check!). Thank you for your attention and help.

**Comment by AlUlkesh** [comment]
Ouch. Good luck with that.

**Comment by AlUlkesh** [comment]
Are you running Gradio  3.23.0 ?

**Comment by AlUlkesh** [comment]
Please follow this thread then: https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/issues/116#issuecomment-1493259585

**Comment by mart-hill** [comment]
For me, while I'm testing WebUI on Gradio 3.23.0, the extension only would show first chosen image data, but no buttons except the folder one. Selecting another image will cause the EXIF information stop appearing and only folder/filename will be shown. No delete button/dialog either (there's a timer that goes infinite in place of EXIF). **PNG Info** tab also doesn't pass any information to the txt2img tab (tested only this tab for now), causes all corresponding txt2img fields (from EXIF) going with timers, infinite, again. This Gradio version seems to be a disaster, truly.

**Comment by AlUlkesh** [comment]
Yes, it's certainly been a major headache.

I assume you are using the latest commits?

Also this PR might be helpful: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9060

**Comment by mart-hill** [comment]
Exactly, both UI and your extension are the latest. I'm trying now, without DreamArtist extension, since I saw walls of errors in the F12 console concerning that extension.
Aaaaand it seems disabling DreamArtist caused the buttons to appear back! Going to test Image Viewer further, since I don't believe **PNG Info** tab if fixable for me at this point. 🙂

**Comment by AlUlkesh** [comment]
I wonder where those javascript errors are coming from. Can you click on a line with `main.js` and see where this takes you?

**Comment by mart-hill** [comment]
> I wonder where those javascript errors are coming from. Can you click on a line with `main.js` and see where this takes you?

Sure! I'll look!

**Comment by AlUlkesh** [comment]
Can you please check if this change solved any of your issues: #126?

**Comment by mart-hill** [comment]
Sure thing, ASAP, when I'm back home. 🙂 
Thank you for your hard work!

**Comment by mart-hill** [comment]
> Can you please check if this change solved any of your issues: #126?

With your hard work and the last fixes you did, the SendTo button to txt2img works almost instantaneously - thank you! 🙂

**Comment by Harvester62** [comment]
I can also confirm that now the Images Browser UI is consistent in all of its tabs, and the deletion buttons are available in each tab. Thank you for your efforts to fix this problem. Please, note that because I am reviewing all the translations for all Script and Extensions, I deactivated all of them in the SD Web UI and therefore I've currently re-activated only your Extension. If I should find out any other problems while re-activating the other extensions, I will let you know. For now, thank you again.
