### ISSUE TITLE
png info not showing with the latest update / old Gradio version

### ISSUE THREAD

**Issue by randima** [AlUlkesh/stable-diffusion-webui-images-browser#116]
version
db40a6e9 (Sat Apr 1 13:48:20 2023)

Not sure what was the last working version but I update all extension to latest today. When I browse images, image does not have any info when selected.

![image](https://user-images.githubusercontent.com/1343603/229301867-2efa3585-f6e1-426a-8c30-3d954b6e860f.png)

**Comment by cjps-br** [comment]
the same problem is happening to me.

**Comment by WojtekKowaluk** [comment]
Same.

**Comment by Wovik253** [comment]
Same

**Comment by AlUlkesh** [comment]
Any info on the console or on the javascript console?

**Comment by kornerson** [comment]
same, I even deleted the extension an redownload it and still it happens. 

Also send to text2image, etc doesnt work.

**Comment by AlUlkesh** [comment]
@kornerson 
Can you go to Settings and check "Image Browser - Print debug logs to the console". Then restart webui and post the complete log, so starting from:

```
c:\tools\Ai\stable-diffusion-webui>webui-user.bat
venv "c:\tools\Ai\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: 955df7751eef11bb7697e2d77f6b8a6226b21e13

```
until the error happens.

Also go into your browser console (probably F12) and check if there are any javascript errors. Except for `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')`, you can ignore that one.

Perhaps we can find a hint then.

**Comment by kornerson** [comment]
did this:

git reset HEAD~3 --hard

and now it works

I will try to help you later @AlUlkesh , but now I have to have some work done with SD and I was in a hurry. 

I can asure you that this git reset has worked, so something changed badly between 3 pushes ago to the git and now.

ASAP I can return to you with some logs 

PS: before this reset I checked the console of chrome and there were a lot of promises  error

**Comment by AlUlkesh** [comment]
Ok, I'll wait. Thanks.

It's still working for me, also on a fresh install. So I can't really do anything until I have more info.

**Comment by cjps-br** [comment]
I use Browser Brave, but when trying with Edge, the image information does not appear either.

I don't know how to operate the browser console properly, but I noticed that when I clicked on an image, an error like this one appears:

image_browser.js?1680368628.2679555:76 Uncaught (in promise) TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at image_browser_run_after_preview_load (image_browser.js?1680368628.2679555:76:8)
    at image_browser_get_current_img (image_browser.js?1680368628.2679555:87:5)
    at async eval (eval at <anonymous> (index.4395ab38.js:75:2081), <anonymous>:3:14)
    at async index.4395ab38.js:34:32404


--------------------------
my operating environment is this:
python: 3.10.6  •  torch: 1.13.1+cu117  •  xformers: 0.0.16rc425  •  gradio: 3.16.2  •  commit: [a9fed7c3] •  checkpoint: [0aecbcfa2c]

**Comment by AlUlkesh** [comment]
@cjps-br 
Are you running the latest version of webui?

You're showing Gradio 3.16.2. It should currently be  3.23.0.

So either you are running an old version of webui, some other extension has installed an old Gradio version or there's some general mixup in your installation.

**Comment by zejacky** [comment]
I have the same "issue" mentioned. No PNG Infos. However I use also gradio: 3.16.2.

Do we need to update gradio? If yes, I would like to know how. (Didn't found something yet)

Thank you very much.

**Comment by cjps-br** [comment]
> 

I even installed the webui version that updated gladio to 3.23.0, but several problems with the interface and extensions started to occur (this being reported in the webui questions) so I went back to a previous webui version (commit: a9fed7c3) where everything worked. Problems with the "stable-diffusion-webui-images-browser" extension started to occur today after I updated the version. I was wondering if there is a way to return to a previous commit of the extension.

**Comment by nickion** [comment]
Problems here as well. I can get info for one image after a page reload, but requesting for a second the spinner/loading bar (that appear to be new or different) for the file path gets stuck loading forever with no info is showing. It immediately had the feel of a promises issue whereby the UI as a whole is waiting for all promises to resolve, but one doesn't (i.e. the file path field), and so nothing works after that. Sure enough others are indeed reporting promises related errors from the console.

**Comment by WojtekKowaluk** [comment]
I'm also on webui version before gradio update, images browser worked fine until today. if you can keep comapatibility with older gradio that would be great because latest webui still have many issues.

**Comment by randima** [comment]
I am not what fixed it, but doing these fixed it for me.
I did a 
git pull on webui 
git reset HEAD~3 --hard on the extension
git pull on extension

**Comment by fw910** [comment]
When trying to load an image with gradio 3.16.2, the following JavaScript error appears in the Chrome console:
_Uncaught (in promise) TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at image_browser_run_after_preview_load (image_browser.js?1680399332.2819486:76:8)
    at image_browser_get_current_img (image_browser.js?1680399332.2819486:87:5)
    at async eval (eval at <anonymous> (index.4395ab38.js:75:2081), <anonymous>:3:14)
    at async index.4395ab38.js:34:32404_

So take a look at the code in the function image_browser_run_after_preview_load of image_browser.js:
    _ob.observe(
        gradioApp().querySelectorAll(`#${tab_base_tag}_image_browser_gallery .svelte-gjihhp`)[0],
        { attributes: true }
    )_

It seems the id "#${tab_base_tag}_image_browser_gallery .svelte-**gjihhp**" should be "#${tab_base_tag}_image_browser_gallery .svelte-**1g9btlg**".
The generation info is back after this change.

**Comment by axemaster** [comment]
> I am not what fixed it, but doing these fixed it for me. I did a git pull on webui git reset HEAD~3 --hard on the extension git pull on extension
> 
> but I see these on the console log when loading pages
> 
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach') at ct (Blocks.svelte:214:8) at Blocks.svelte:293:7

This made no difference to me. Still have the issue. Also some timer on the screen that just goes up forever.

**Comment by axemaster** [comment]
Same issue. Mac M1 & Chrome.  Could this be another Firefox incompatibility bug? Chrome is the standard now.
In any case, the image displays fine, just none of its info. If I right click the image and open it by itself, then drag-drop that in the **PNG Info** tab, all the info displays correctly. _That is the work around for now I guess_.

I noticed this issue a few days ago. ¯\_(ツ)_/¯

**Comment by AlUlkesh** [comment]
**For Gradio users < 3.23.0:**

I can't maintain and esp. test two versions of the involved code. I implemented a compatibility for the first few days, so people would have time to update webui and the other extension's maintainer to change the necessary code.

If you want/need to keep using the old Gradio version, please use the last compatible version. To do this, go into the extension's directory and do:
`git checkout 1d5c2e7`

If you later want to undo this, do:
`git checkout master`

**Comment by AlUlkesh** [comment]
If you are having this issue, but are running the current Gradio, please open a new issue, so I can separate these. Thanks.

**Comment by AlUlkesh** [comment]
@zejacky 
> Do we need to update gradio? If yes, I would like to know how. (Didn't found something yet)

Webui should have automatically upgraded you, if you're using a current version.

It checks the `requirements*` files in its main directory and installs those versions.

Are you using some kind of special installation? Anaconda or Docker perhaps?

**Comment by zejacky** [comment]
> @zejacky
> 
> > Do we need to update gradio? If yes, I would like to know how. (Didn't found something yet)
> 
> Webui should have automatically upgraded you, if you're using a current version.
> 
> It checks the `requirements*` files in its main directory and installs those versions.
> 
> Are you using some kind of special installation? Anaconda or Docker perhaps?

Thank you. The problem is solved after I git pull  A1111 to commit 22bcc7be428c94e9408f589966c2040187245d81.
On the other side, gradio 3.23.0 seems very buggy compared to  3.16.2. I have now many other issues inside A1111. 
I will probably go back to the commit I had no issues. (a9fed7c364061ae6efb37f797b6b522cb3cf7aa2 , Tue Mar 14 11:28:13 2023 +0300)

Btw. I'm not automatically git pulling every time I start A1111. 
I put now git log -1 inside webui-user.bat. Do someone have a better idea to check if updates are available, despite of github desktop version like fetch?

**Comment by AlUlkesh** [comment]
> Do someone have a better idea to check if updates are available, despite of github desktop version like fetch?

Try `git remote update` followed by `git status -uno`

That should give you this info:
`Your branch is behind 'origin/master' by 389 commits, and can be fast-forwarded.`

**Comment by Davey212** [comment]
python: 3.10.10  •  torch: 1.13.1+cu117  •  xformers: 0.0.17.dev464  •  gradio: 3.23.0  •  commit: [22bcc7be]
and df3d5413 images browser

Everything seems to be ok except the First/Prev/Next/End Page won't load thumbnail pages, only refresh the first image I clicked on after first loading A1111, and I go to Image Browser tab

**Comment by AlUlkesh** [comment]
I suspect so.

I don't know what you're running this on, but for most systems webui is an easy fresh install these days. So you might want to consider this in the meantime.

**Comment by zejacky** [comment]
> I suspect so.
> 
> 
> 
> I don't know what you're running this on, but for most systems webui is an easy fresh install these days. So you might want to consider this in the meantime.

Exactly. After all I did a fresh a1111 git clone, and all was working like a charm. Even other failures I had "disappeared" 😄

**Comment by hstdt** [comment]
> I suspect so.
> 
> I don't know what you're running this on, but for most systems webui is an easy fresh install these days. So you might want to consider this in the meantime.

How can I keep outputs and Generation Info? Thanks.

**Comment by AlUlkesh** [comment]
> > I suspect so.
> ~How can I keep outputs and Generation Info?~
> 
> I find out that prompt info is inside png string😄

However, if you used the ranking feature and personal paths it would be best to copy the wib.sqlite3 database over.

**Comment by hankhoffman87** [comment]
SORRY! TYPO for step 6. it should read as follows: 

6. then type: git pull  and PASTE the string of numbers and letters you selected. HIT ENTER and reload WEB UI and it will work. If not try another commit string.

**Comment by AlUlkesh** [comment]
@hankhoffman87:
So... did what I wrote above not work for you? https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/issues/116#issuecomment-1493259585

**Comment by constant-null** [comment]
ImageBrowser seems to break new webui (specifically image preview), and for it to work it requires new webui...

**Comment by AlUlkesh** [comment]
For anyone using the new Gradio version and still having problems: Can you please check if this change solved any of your issues: #126?

**Comment by Davey212** [comment]
[83419e4] fixed image browser issue for me!

**Comment by slurpey** [comment]
@Davey212 would you mind elaborating?  I'm trying to fix it but I don't know what to do with you answer ;(

**Comment by chuanshendongman** [comment]
me too
