### ISSUE TITLE
分支前的图片信息没有了

### ISSUE THREAD

**Issue by lwstudy** [AlUlkesh/stable-diffusion-webui-images-browser#119]
之前使用的[图库浏览器](https://github.com/yfszzx/stable-diffusion-webui-images-browser)，
然后重装后从可用里下的该插件，但是无论是之前备份的图还是新上次的图都没有显示图片的信息，即正反面tag和各项参数

**Comment by AlUlkesh** [comment]
I'm using DeepL here, so please excuse any errors.
Automatic1111's webui has recently updated to Gradio 3.23.0. So I had to change this extension accordingly and it is now at a point where it will no longer work with the old Gradio. Is your installation of webui current?

我在这里使用DeepL，所以请原谅任何错误。
Automatic1111的webui最近已经更新到Gradio 3.23.0。所以我不得不对这个扩展进行相应的修改，现在已经到了无法与旧版Gradio配合的地步。你安装的webui是最新的吗？

**Comment by lwstudy** [comment]
Well, maybe it's not a problem, it just needs to install the last version of this plug-in for the time being, because the latest webui development version has been updated, many plug-ins are not supported yet,so no updates webui for the time being
