### ISSUE TITLE
console: You have unused kwarg parametres

### ISSUE THREAD

**Issue by davehornik** [AlUlkesh/stable-diffusion-webui-images-browser#121]
Please can we get a fix for this console spam or is this issue related to something else?
```
D:\Stable WEBUI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'equal_height': True}
  warnings.warn(
D:\Stable WEBUI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Tab, please remove them: {'open': False}
  warnings. Warn(
  ```

`Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]`
`gradio: 3.23.0`

**Comment by AlUlkesh** [comment]
I doubt that is from this extension.

Also I'm not having those.

**Comment by davehornik** [comment]
That is kinda weird tho, since I only left this ext active and the errors are there. Interesting.

**Comment by davehornik** [comment]
Okay nevermind, somehow CotrolNet extension was still active even tho I got it unchecked in UI.
and thats printing the error.
Sorry for the trouble.
