### ISSUE TITLE
Image Browser tab completely disappeared

### ISSUE THREAD

**Issue by nemesiscompletion** [AlUlkesh/stable-diffusion-webui-images-browser#123]
I updated the extension last night and I noticed there's no more PNG information, send to txt2img or whatever
Still there was Image Browser Tab

I noticed there's newer update, so I just updated it
Now, there's nothing
Image Browser tab just disappeared
Restarting Webui didn't do anything

Also, it disappeared from Settings tab for its options
![20230403_113937](https://user-images.githubusercontent.com/115454608/229559578-15aeaf4d-9880-40b8-9dbd-6e339ca84388.jpg)

**Comment by AlUlkesh** [comment]
I made the requirement message show up in the UI now. I hope this prevents further confusion.

![image](https://user-images.githubusercontent.com/99896447/229612093-945b9350-56d2-401d-9a9e-df26f3425885.png)
