### ISSUE TITLE
Gradio .then

### ISSUE THREAD

**Issue by AlUlkesh** [AlUlkesh/stable-diffusion-webui-images-browser#126]
I just went through the last several pages of Gradio commits and saw that they now have a .then function for events.

I'm gonna change the image browser code to use this. This should make things easier, faster and less prone to synchronization issues.

I'm hoping it might solve some of the current issues some users have.

**Comment by AlUlkesh** [comment]
Well... this turned out to be a major rework instead of a small change. A few details:
- The normal _js function from Gradio runs the javascript first and then the python function. With .then you can run them the other way around. Before this change I had to use a custom sync scheme for this.
- Since webui's update to the new Gradio, it does "something" at the beginning. This can be very short or rather long. And if you try to use the image browser, before it's finished the UI can get stuck. I've now blocked any user interaction, before this time is over.
- I have (at least for now) removed the "load hiding", since it interfered in unpredictable ways with eventlistener function. Once this is all stable again I can look back into it

**Comment by forsurefr** [comment]
After the last commit the image browser is stuck on 'Waiting for webui...'. How long can it take for startup?

**Comment by AlUlkesh** [comment]
In my tests it took between instant and 50 seconds for webui to be "ready".

**Comment by forsurefr** [comment]
it is not loading at all, even after an hour. i deleted all images and even the sqlite file but it is still not loading.

**Comment by davehornik** [comment]
> Did I mention how frustrating this is? It's working flawlessly for me for now - and seems completely broken for you. This has been such a common theme with these Gradio changes 😭
> 
> I'll have to think about this, what kind of debug info would help me, since I can't test it myself.
> 
> Maybe I'll try to find out what that "waiting period" at startup is. But I'm afraid that's inside Gradio with their unreadable code.

Could try to run it thru debug myself and see what's happening while its starting that infinite loading.

**Comment by missionfloyd** [comment]
> * I have (at least for now) removed the "load animation hiding", since it interfered in unpredictable ways with eventlistener functions. Once this is all stable again I can look back into it

Gradio components now have a `show_progress` parameter to hide the loading animation.

**Comment by AlUlkesh** [comment]
Can you follow the new debug info guide: #130 and post your logs?

**Comment by AlUlkesh** [comment]
Can you all try the latest update please: #135

**Comment by forsurefr** [comment]
> Can you all try the latest update please: #135

The latest update did solve the loading issue. There are still some loading animations in the image browser tabs (loading metadata) but it is a lot better.
