### ISSUE TITLE
Issue with Gradio

### ISSUE THREAD

**Issue by woofodus** [AlUlkesh/stable-diffusion-webui-images-browser#127]
I wasn't able to use the image browser after doing all the recent updates, and seen that Gradio was on the newer version. After updating, it seems that my image browser works again but the scale of my UI is really off. 
![Opera Snapshot_2023-04-06_170828_127 0 0 1](https://user-images.githubusercontent.com/129104928/230498951-634875d5-ea52-4e4b-b216-d16ad02220f3.png)
![Opera Snapshot_2023-04-06_171302_127 0 0 1](https://user-images.githubusercontent.com/129104928/230498954-f28cb7cd-ede9-467c-ada2-a64a851e97fd.png)

**Comment by AlUlkesh** [comment]
Can you please check if this change solved any of your issues: #126?

**Comment by woofodus** [comment]
> Can you please check if this change solved any of your issues: #126?

Same result. Could this be an larger issue with Gradio or SD? I just tried to remove image browser extension and load back into to latest Gradio and it's still doing it. So must be something on my end with an extension or something.

**Comment by AlUlkesh** [comment]
You could try a fresh install into a new directory to make sure. And if possible, best to just let webui's installation do its thing. No Anaconda or Docker.

**Comment by woofodus** [comment]
> You could try a fresh install into a new directory to make sure. And if possible, best to just let webui's installation do its thing. No Anaconda or Docker.

After doing a fresh install into a new directory I can confirm everything is working now, appreciate it~

**Comment by AlUlkesh** [comment]
Great. Thanks for the feedback.
