### ISSUE TITLE
after installed this extension, the base model can't be loaded.

### ISSUE THREAD

**Issue by sunhaha123** [AlUlkesh/stable-diffusion-webui-images-browser#134]
![image](https://user-images.githubusercontent.com/27773261/230876620-711e2386-5a6b-40f3-a650-b3ea448a12c2.png)

**Comment by AlUlkesh** [comment]
Can you follow the new debug info guide: https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/discussions/130 and post your logs?

**Comment by AlUlkesh** [comment]
Can you try the latest update please: #135

**Comment by AlUlkesh** [comment]
You're using miniconda. That had been a problem for myself when I first upgraded to the new Gradio version.

Can you try a fresh install into a new directory to make sure. And just let webui's installation do its thing. No Anaconda or Docker.
