### ISSUE TITLE
Option to disable processing toast?

### ISSUE THREAD

**Issue by ice051128** [AlUlkesh/stable-diffusion-webui-images-browser#139]
See screenshot for reference
![Screenshot_7](https://user-images.githubusercontent.com/49018832/233291315-4005d3b7-bb56-467c-acf1-d024c5c4a318.png)

**Comment by AlUlkesh** [comment]
An option to turn the progress indicator off has been added:

![image](https://user-images.githubusercontent.com/99896447/236667259-44a34d13-92ab-424a-897f-b3492f27dab7.png)
