### ISSUE TITLE
Minimum aesthetic score doesn't seem to filter

### ISSUE THREAD

**Issue by scpedicini** [AlUlkesh/stable-diffusion-webui-images-browser#140]
https://user-images.githubusercontent.com/2040540/233529576-b968b6ee-0b85-4f98-aa67-34a383630255.mp4

I have the latest version, and after assigning a rank value to images, I can't seem to use the Aesthetic score to filter. It never shows any images. Demo in video.

**Comment by AlUlkesh** [comment]
Thanks for the video. That always helps.

Those are two different things. The Ranking filter refers to the manually set rankings, that is the rankings you can make with these buttons:
![image](https://user-images.githubusercontent.com/99896447/233534854-49ddb80a-ecdd-4ef0-9bad-3cb57b316457.png)


Aesthetic Score is an automatic scoring by extensions such as
https://github.com/vladmandic/sd-extension-aesthetic-scorer
or
https://github.com/tsngo/stable-diffusion-webui-aesthetic-image-scorer

**Comment by scpedicini** [comment]
@AlUlkesh wow, I had no idea anything like that existed thanks - maybe a tooltip on hover over it to explain its related to an extension?

Basically, I just want to filter any images that have been "manually ranked" by me. It would make it easier to just see a list of the images that I've looked at and assigned rankings to *so far*. I'd rather not add them to Favorites since that physically moves them to a new folder.

Ranking Filter "All" or "None" doesn't seem to cover that scenario.

**Comment by AlUlkesh** [comment]
@scpedicini Yeah, one of these day I'll get around to those tooltips...

I added a min and max for ranking. Let me know, if this works for you.
