### ISSUE TITLE
Respecting subfolder depth gone ... ?

### ISSUE THREAD

**Issue by Woisek** [AlUlkesh/stable-diffusion-webui-images-browser#141]
I'm using [vlads fork](https://github.com/vladmandic/automatic) now and the image browser is now integrated.
What I noticed, is, in the settings, "Include images in sub directories" checkbox seems to be global (again)?
Because the "others" folder should rely on the subfolder depth definition, but with "Include images in sub directories" checked, all folders will be display no matter the depth. If it's turned off, I can see tx2img images and the like, but in "others", I only see images in the root folder, and for defined subfolders with depth value, I don't see any images.
Is this a bug?

**Comment by AlUlkesh** [comment]
Hmm, I haven't touched that code in a long time:
https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/blob/0029d95a5f720b387c530e916a9e166277aa66e2/scripts/image_browser.py#L407

Did you set the settings like you want them and then restart webui first, before trying again?

**Comment by Woisek** [comment]
I had to restart often lately, but yeah, I think so. 🤪 Just to recap again: The "Include images in sub directories" checkbox affects now what section?

**Comment by AlUlkesh** [comment]
Subdirectories are read if

- the checkbox is set and you are not in the "Others" tab
- or if you are in the "Others" tab, according to the depth setting

**Comment by Woisek** [comment]
OK, I made sure, the checkbox is set and completely restarted WebUI and opened a new tab.
Result:
In text2img ... I can see all images from all folders ✔
In Others, choosing a subfolder of root with a depth value, I see now the images ✔
In Others, choosing the root itself, where only 3 images are, I get 311 pages, because it displays _all_ images from _all_ subfolders, alltough the depth value is set to 0. ❌

![Zwischenablagebild (1)](https://user-images.githubusercontent.com/122026301/233650293-6e47529c-fda5-471e-9af4-0457ee0826a7.png)

Suggestions? 🙂

**Comment by AlUlkesh** [comment]
When I try that on webui root I get console errors, since there seem to be some non-pictures with picture-extensions in there. No errors for you?

**Comment by Woisek** [comment]
Just to clear up any ambiguities: I refer to the folder shown in the screenshot as "root". It contains many other folders with the respective images. 🙂
And no, no errors in the console, even with a prior existed .csv file.

**Comment by AlUlkesh** [comment]
Well, let's start with a debug output: https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/discussions/130

**Comment by Woisek** [comment]
> Well, let's start with a debug output: #130

2023-04-22-08:51:56 image_browser.py: debug_level: 4

😶
That's all.

**Comment by AlUlkesh** [comment]
That's... interesting, to put it mildly. Seem like something in vlad's fork is suppressing the debug info. Let me go and search for thatg.

**Comment by Woisek** [comment]
Thanks.

**Comment by AlUlkesh** [comment]
https://github.com/vladmandic/automatic/discussions/372

**Comment by AlUlkesh** [comment]
I've just implemented a workaround for the debug issue.

Please try again, like it says in #130, but before replicating your issue, head to the Maintenance tab and press `Restart debug`.

**Comment by Woisek** [comment]
OK, now there is some results. I hope you can find something.

[image_browser.log](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/files/11309736/image_browser.log)

**Comment by Woisek** [comment]
Thanks, it's working again. 🎉
