### ISSUE TITLE
Feature request:support for ImageReward

### ISSUE THREAD

**Issue by sdbds** [AlUlkesh/stable-diffusion-webui-images-browser#146]
https://github.com/THUDM/ImageReward
ImageReward is the first general-purpose text-to-image human preference RM, which is trained on in total 137k pairs of expert comparisons.

It outperforms existing text-image scoring methods, such as CLIP (by 38.6%), Aesthetic (by 39.6%), and BLIP (by 31.6%)

![image](https://user-images.githubusercontent.com/8085926/234455800-26d55cd9-c160-4ac0-acf3-0c993c1c4eb9.png)

**Comment by AlUlkesh** [comment]
Very interesting. I'll look into it.

**Comment by AlUlkesh** [comment]
@sdbds How would you expect this to work?

Have a button when an image is selected to score that image?

Or have all images in a tab be scored at the same time?

Or... ?

**Comment by sdbds** [comment]
> 
I think it would be better to automatically score all ungraded images at the same time, so as not to affect manually scored images.

**Comment by AlUlkesh** [comment]
@sdbds I just implemented the first version of this. Can you test, if that works, like you expected it to?

**Comment by AlUlkesh** [comment]
Settings for preferred scoring method:
![image](https://user-images.githubusercontent.com/99896447/236394980-3a0feb52-9e32-4d85-89d7-44afc4a9532f.png)

After clicking "First page", this button becomes available:
![image](https://user-images.githubusercontent.com/99896447/236395269-a10865c3-5572-4014-b5d6-524bd56674ea.png)

Generating can take a fairly long time, depending on number of images. After that you can use the sorting and filter options.

**Comment by missionfloyd** [comment]
Shouldn't it be optional, like controlnet?

**Comment by AlUlkesh** [comment]
I think it is? If you never press the Generate ImageReward button nothing will be done with Image Reward.

**Comment by missionfloyd** [comment]
The controlnet buttons don't show up unless controlnet is installed. You have it disabling the button if imagereward isn't installed, but also installing it as a dependency.

**Comment by AlUlkesh** [comment]
The disabling when not installed, is just a fallback. I had some users not being able to get send2trash installed, which then broke the extension at the import.

I think this is different than controlnet. That's its own webui extension. For Image Reward everything is contained within the Image Browser extension.

**Comment by sdbds** [comment]
> @sdbds I just implemented the first version of this. Can you test, if that works, like you expected it to?

Traceback (most recent call last):
  File "H:\novelai-webui-aki-v2\py310\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\novelai-webui-aki-v2\py310\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "H:\novelai-webui-aki-v2\py310\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\novelai-webui-aki-v2\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\novelai-webui-aki-v2\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\novelai-webui-aki-v2\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\novelai-webui-aki-v2\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 1059, in generate_image_reward
    image_reward_model = ImageReward.load("ImageReward-v1.0")
  File "H:\novelai-webui-aki-v2\py310\lib\site-packages\ImageReward\utils.py", line 65, in load
    model_path = ImageReward_download(_MODELS[name], download_root or os.path.expanduser("~/.cache/ImageReward"))
  File "H:\novelai-webui-aki-v2\py310\lib\site-packages\ImageReward\utils.py", line 41, in ImageReward_download
    hf_hub_download(repo_id="THUDM/ImageReward", filename=filename, local_dir=root)
  File "H:\novelai-webui-aki-v2\py310\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "H:\novelai-webui-aki-v2\py310\lib\site-packages\huggingface_hub\file_download.py", line 1259, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

i got a network error,not sure if it is my network problem.i will try it soon

**Comment by sdbds** [comment]
index.js:67 POST http://127.0.0.1:7860/run/predict 500 (Internal Server Error)
i think this is a bug because of a1111 webui 1.10,i will use 1.0.0 to try again

**Comment by AlUlkesh** [comment]
I just deactivated the Image Reward Generation functionality again.

I realized it keeps installing a newer version of transformers than what is set as a webui requirement.

I'll re-activate it again, once the requirements are the same.

(I honestly had no idea an extension could "overrule" the main module as far as systemwide requirements go.)

**Comment by halr9000** [comment]
> After clicking "First page", this button becomes available:

oof yeah I saw that in the console that it messed with my deps. Do you have the steps to back out the change btw? Or is it easier to rm venv and start over? 

Also for the record, I was never able to get the generate button to function. Perhaps this was to be expected?

Unsure what you have deactivated, as I do see image reward options in the browser UI.

**Comment by AlUlkesh** [comment]
In theory, webui should install its required transformers version on the next startup.

I removed the install-part and anything related to actively use ImageReward. I left the UI as is, so people who used it before can still filter on it.
