### ISSUE TITLE
Feature Request: Image dimensions and other quick info when hovering over image?

### ISSUE THREAD

**Issue by sidcarton1587** [AlUlkesh/stable-diffusion-webui-images-browser#148]
Especially when looking for poses to feed to ControlNet it's helpful to know the dimensions of an image as I hover the mouse over it in the gallery view, since collections of poses sometimes include images of varying sizes. Even something as simple as a bit of text just below the gallery with "width x height" would be useful.

**Comment by AlUlkesh** [comment]
@sidcarton1587 I just implemented the tooltip version. Can you test, if that works, like you expected it to?
