### ISSUE TITLE
Wrong aspect ratio in preview window

### ISSUE THREAD

**Issue by edisonchan** [AlUlkesh/stable-diffusion-webui-images-browser#151]
image browser version: 57040c31 (Tue Apr 11 18:15:08 2023)
webui version: Automatic 1111 v1.1.0

![image](https://user-images.githubusercontent.com/8596506/235603607-bb562ca8-5646-4bcd-ba03-214396d4bcbc.png)

**Comment by AlUlkesh** [comment]
That's already fixed. Please update to the current image browser version.
