### ISSUE TITLE
Optimized images never become original

### ISSUE THREAD

**Issue by lihaoyun6** [AlUlkesh/stable-diffusion-webui-images-browser#152]
Hello,
When I enable "Use optimized images in the thumbnail interface", all images in the gallery become thumbnails, which is great.
But when I click on an image, it will always be shown as a thumbnail instead of loading the original image. Is this a bug or a feature?

**Comment by AlUlkesh** [comment]
Not a feature...

I'll check it out, when I get around to it. I usually don't use scaled thumbnails.

**Comment by AlUlkesh** [comment]
I just checked. It works normally on my end. Please post a log file, as explained here: #130

**Comment by QinCaii** [comment]
same here

**Comment by QinCaii** [comment]
oh it fixed, just pull the repo manually
