### ISSUE TITLE
recommended to support files of type ". Mp4" in the "Other" tab

### ISSUE THREAD

**Issue by anbuzz** [AlUlkesh/stable-diffusion-webui-images-browser#156]
Because some plugins can generate. mp4 video files

**Comment by AlUlkesh** [comment]
That has come up before, but ran into problems; #87 

Perhaps you can bring some new ideas to it?

**Comment by anbuzz** [comment]
> That has come up before, but ran into problems; #87
> 
> Perhaps you can bring some new ideas to it?

Well, my idea is to first do this in the "Other" tab, which at least ensures that the video file is browsable and does not disrupt the content classification of the previous tab. It also reduces the complexity of modifying the code. In the future, the video can also be listed as a separate tab
Now with my modifications, I can display video thumbnails, but to play the video, I need to further analyze how these web page elements are designed and distributed

**Comment by AlUlkesh** [comment]
Gradio has a separate video element. I wonder if I could make the full-size-image invisible and a video element visible on click. I can try this out.

**Comment by AlUlkesh** [comment]
See #241
