### ISSUE TITLE
Delete can delete wrong image

### ISSUE THREAD

**Issue by AlUlkesh** [AlUlkesh/stable-diffusion-webui-images-browser#159]
@JoeyLearnsToCode:

> But now I find another problem, the "Generation Info" part update with 1s delay after switching image(which is realtime and fast).
Within that second of delay, delete button seems to delete the previous image(before switch), not the new one(after).

I already fixed this bug twice. I wonder what changed to make it reappear :anguished:

**Comment by bryanray** [comment]
this plugin is so funny, i wonder how the original repo owner make it with all these hard to maintain feature for other forker :)

**Comment by JoeyLearnsToCode** [comment]
I blame it on gradio instead of image browser.

**Comment by AlUlkesh** [comment]
Yeah, I'm actually impressed the original author was able to pull this off, despite the massive Gradio limitations.

This commit should fix this.

**Comment by bryanray** [comment]
please make the delete option using "recycle bin" as default :)

**Comment by AlUlkesh** [comment]
I have no idea, why this wasn't the default option already... I changed it, thanks.
