### ISSUE TITLE
[Feature request] It would be nice to add an option to disable EXIF data scanning.

### ISSUE THREAD

**Issue by toyxyz** [AlUlkesh/stable-diffusion-webui-images-browser#16]
I keep a lot of generated image files in a folder. However, when I run the image browser, it takes too much time to scan Exif. "No EXIF in PNG/JPG or txt file for" doesn't end. Sometimes it even stops working. I think it would be nice to have an option to decide whether or not to scan.

**Comment by AlUlkesh** [comment]
I've actually just looked at that code. I get the feeling it sometimes scans more than it should. I'll test this some more.

But in the meantime, here's the option:
![image](https://user-images.githubusercontent.com/99896447/216794866-4f39b1d0-4af5-4ebe-a4d2-48a192cdc19b.png)

**Comment by AlUlkesh** [comment]
I found the bug. You can now also let it scan one more time, after that it should be much faster.

#17
