### ISSUE TITLE
closed not the repo coding issue

### ISSUE THREAD

**Issue by bryanray** [AlUlkesh/stable-diffusion-webui-images-browser#161]
closed not the repo coding issue

**Comment by AlUlkesh** [comment]
I deactivated it yesterday: https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/issues/146#issuecomment-1537209083

However it should still not output that message. Are you running the latest image browser version?

**Comment by bryanray** [comment]
it is not a issue with your coding, it is mine, i use this enclosed python+git from a1111=
"https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.0.0-pre"  
doesn't have the virtual environment (venv) 

it said it cannot find pip.... when i type cmd in the windows path in the python root folder...

**Comment by bryanray** [comment]
![image](https://user-images.githubusercontent.com/1768531/236668586-e6bd336a-b5ec-4855-8f39-b59203bd4506.png)
![image](https://user-images.githubusercontent.com/1768531/236668598-6d861ecd-8784-4229-87af-0f553beef357.png)

files and folders seems different than the installer python...
i like this version 
"https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.0.0-pre"
cos it is portable, a1111 release this for people cannot install python and git on the computer....
it also means it is "portable" which is sexy to me:)

**Comment by bryanray** [comment]
it was not installed
