### ISSUE TITLE
Separating parameters

### ISSUE THREAD

**Issue by AlUlkesh** [AlUlkesh/stable-diffusion-webui-images-browser#163]
@bryanray:
> could you add this feature: separating parameters.
![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/99896447/1d4d4a42-cfe0-4b03-9c2b-a4d35cb2e834)

**Comment by bryanray** [comment]
you were such a lovable dude :)

I really use this extension alot, the ui/ux is not so great.

**Comment by AlUlkesh** [comment]
That's a maintainer option, once I've decided what I think the category is...

**Comment by bryanray** [comment]
wow, i thought it is for everyone, must be so much work for maintainer....

**Comment by AlUlkesh** [comment]
Solved with #252
