### ISSUE TITLE
[enhancement] remove fitted-full-page preview header, it is driving image down, shows a extra/double scroller

### ISSUE THREAD

**Issue by bryanray** [AlUlkesh/stable-diffusion-webui-images-browser#164]
![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/1768531/462f8cea-1ece-4ef6-9609-c562331e9a15)

buttons can be floated, with alpha/transparency, still locate on top left corner.

**Comment by bryanray** [comment]
i dont know how to make a color label, looks good

**Comment by AlUlkesh** [comment]
This is the image viewer from webui. If you want it changed you should take it up with the webui fork you are using.

**Comment by bryanray** [comment]
thanks
