### ISSUE TITLE
Generation Info Unstable on Android

### ISSUE THREAD

**Issue by abartholet** [AlUlkesh/stable-diffusion-webui-images-browser#165]
I have come across several issues with the images browser when using it on Android using both Firefox and Chrome (I will break them into separate issues) which appear to correspond with the Gradio upgrade back in March.  I have not had these issues when using it on the desktop.

The generation info box becomes unresponsive if you quickly switch between images without waiting for it to finish loading.
![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/49493738/94ccfdd8-6815-4424-b145-4cf4b66c1e32)

If you try and use the various sendTo* functions when it is in this state the input boxes do not get populated and become unresponsive.
![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/49493738/a70de370-102a-46bb-8c62-5f829ae81d77)

The dropdown for Additional Generation Info does not appear to be affected and continues to work properly.
![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/49493738/ebfd6f1f-8e97-4ec8-83a4-2600e2829cba)

The only way to fix it is to reload the page.

Things I've tried:
* disabling the progress indicator
* using optimized images
* rebuilding the exif cache
* generating txt files alongside images
* a clean install of both stable-diffusion-webui and the images browser extension (only) 

OS: Android 12; Pixel 3a
Browsers: Firefox 112.2.0 and Chrome 113.0.5672.77
stable-diffusion-webui: 5ab7f213bec2f816f9c5644becb32eb72c8ffb89
stable-diffusion-webui-images-browser: c751a9eeedef738fd0a731db1dd65690690b6161

**Comment by AlUlkesh** [comment]
For this one a debug file might give some clues. Can you one post one, as described here: https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/discussions/130

**Comment by abartholet** [comment]
I increased the debug level and restarted the webui, but now I get the following UnboundLocalError when it starts up.

```
Image Browser: ImageReward is not installed, cannot be used.
2023-05-10-20:01:18 image_browser.py: debug_level: 4
2023-05-10-20:01:18 image_browser.py: /home/abar/stable-diffusion-webui/venv/bin/python3.10 3.10.10 (main, Mar 26 2023, 07:38:38) [GCC 10.2.1 20210110]
2023-05-10-20:01:18 image_browser.py: Linux #1 SMP Debian 5.10.178-3 (2023-04-22)
2023-05-10-20:01:18 image_browser.py: Webui 5ab7f213bec2f816f9c5644becb32eb72c8ffb89
Error loading script: image_browser.py
Traceback (most recent call last):
  File "/home/abar/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/abar/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/abar/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser/scripts/image_browser.py", line 238, in <module>
    restart_debug("startup")
  File "/home/abar/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser/scripts/image_browser.py", line 225, in restart_debug
    logger.debug(f"Image Browser {image_browser_commit_hash}")
UnboundLocalError: local variable 'image_browser_commit_hash' referenced before assignment
```

**Comment by AlUlkesh** [comment]
That's odd. I've caught the error in the latest update. Can you try again?

**Comment by abartholet** [comment]
In this instance it started on the first image I selected, but I still switch back and fourth between it an another image in case it gives you any more useful information in the logs.

[image_browser.log](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/files/11470979/image_browser.log)

**Comment by eadnams22** [comment]
Running with gradio queues disabled (the command line arg depends on the webui you’re using) is the only way I could workaround this, still slow AF with WebKit browsers(safari, etc), but at least it mostly works otherwise in other browsers.

**Comment by abartholet** [comment]
> Unlike the OP, I have the same problem on my desktop system (Windows 10, Chrome 113). Otherwise every single observation is identical to OP:
> 
>     * it apparently began with the Gradio upgrade
> 
>     * the bug usually triggers when clicking a new image before the previous one has loaded
> 
>     * infinitely spinning loader icon
> 
>     * standard info boxes do not get populated, but Additional Generation Info works
> 
>     * the only fix is to reload the page (which loses all changes in other tabs)
> 
> 
> This happens very frequently to me and is the only major pain point of an otherwise amazing extension.

Thanks for the addition info, I forgot to mention that I've only tried it on Firefox (102.11.0esr) on the desktop and since I didn't have any issues there I didn't try it in a different browser.

**Comment by abartholet** [comment]
> Running with gradio queues disabled (the command line arg depends on the webui you’re using) is the only way I could workaround this, still slow AF with WebKit browsers(safari, etc), but at least it mostly works otherwise in other browsers.

Thanks for the workaround, it is working on on Android with gradio queues disabled.  Hopefully there will be solution eventually, but at least it's working and that is good enough for now.
