### ISSUE TITLE
Image Width Not Fitting Screen on Android

### ISSUE THREAD

**Issue by abartholet** [AlUlkesh/stable-diffusion-webui-images-browser#169]
I have come across several issues with the images browser when using it on Android using both Firefox and Chrome (I will break them into separate issues) which appear to correspond with the Gradio upgrade back in March.  I have not had these issues when using it on the desktop.

When viewing an image full screen it no longer fits the width to the screen causing it to over-scan.  You can still see the full image by scrolling over, but it's not what it used to do and I'm guessing is not the desired behaviour.

![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/49493738/176520bb-b834-44c7-9fc5-76eadd9995dd)

![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/49493738/f88fefe5-71fc-4c49-8d5f-5ebd1937088d)

![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/49493738/366d4255-3d7f-4e2c-8205-754701fdcc70)

OS: Android 12; Pixel 3a
Browsers: Firefox 112.2.0 and Chrome 113.0.5672.77
stable-diffusion-webui: 5ab7f213bec2f816f9c5644becb32eb72c8ffb89
stable-diffusion-webui-images-browser: c751a9eeedef738fd0a731db1dd65690690b6161

**Comment by AlUlkesh** [comment]
Thanks for separating the issues, and giving examples for everything.

**Comment by AlUlkesh** [comment]
Does this issue still exist for you? Looks fine on my Pixel.

**Comment by abartholet** [comment]
Ah, yes this seems to have been fixed at some point and I didn't even notice it.  Thanks.
