### ISSUE TITLE
Hangs when deleting pictures and is super slow

### ISSUE THREAD

**Issue by SwannSchilling** [AlUlkesh/stable-diffusion-webui-images-browser#170]
After the latest updates the extension became so slow I can barely use it, also it hangs in an endless loop when I am trying to delete pictures! It was so useful before, I would really love to have its original functionality back!

**Comment by AlUlkesh** [comment]
Please post a debug file, as described here: #130

**Comment by SwannSchilling** [comment]
Hey, I updated PyTorch and xformers and things seem to be running fine now, I will close the issue! Thanks for pointing me to the debug, next time I will directly attach the debug info!

**Comment by AlUlkesh** [comment]
Ah, very good. Thanks for letting me know!

**Comment by PaperOrb** [comment]
I'm getting a ton of lag still. I'm on 7da8aec6.
