### ISSUE TITLE
No generation info data or filenames shown

### ISSUE THREAD

**Issue by orfeaus** [AlUlkesh/stable-diffusion-webui-images-browser#173]
The image browser loads normally and displays images that can be selected and scrolled, but when I click on an image, it never loads the file name or any of the generation information - which is what I primarily use the extension for.

It's been like this on my machine for some time now and updating to the most recent version hasn't fixed it.

(It's possible that it's a MacOS issue since I don't see any other reports of it.)

**Comment by rexorp** [comment]
I am having the same issue on PC. I just noticed it today and it apparently started 3 days ago.

**Comment by mrcaipeng** [comment]
I counted the same promble as the above description. thanks for your support this.

**Comment by AlUlkesh** [comment]
Webkit based browsers seem to have a problem.

However on PC it should work. If not, please post a full debug file, as described here: #130
