### ISSUE TITLE
Checkbox?

### ISSUE THREAD

**Issue by LLKoder** [AlUlkesh/stable-diffusion-webui-images-browser#179]
What is the purpose of having a `Checkbox` on each page at the bottom of the extension?

Example:
![2023-05-24_18-10](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/50442676/115e8429-9d6a-414e-8f95-d84593293508)

**Comment by AlUlkesh** [comment]
That's a bug - shouldn't be visible. I'll change it on the next update.

**Comment by AlUlkesh** [comment]
Should be gone in the latest version.
