### ISSUE TITLE
[BUG] same label name causes wrong img_path value.

### ISSUE THREAD

**Issue by KohakuBlueleaf** [AlUlkesh/stable-diffusion-webui-images-browser#181]
I'm not sure if this is caused by some update in the dev branch of sd-webui.
But when I using your image browser in these weeks. it looks like all the tab are reading for same path and I never take a closer look on it.

And I just find that since all the img_path object which are all textbox. and share same label name 
![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/59680068/2b015070-9087-48dc-8f3d-f817d8972851)

sd-webui will use "same value" for all the img_path. which will causes some severe bugs.(if you set img_path to "" on others. it will be broken)

and basically I think we have two way to solve this things.
1, use state for non-others tabs. (I'm using this solution)
2, use different label name on different tab (but crashed ui-config.json can still cause this kind of bug)

If you think 1 is ok I can make a pr for it.

**Comment by AlUlkesh** [comment]
I'm afraid I don't quite understand. And I currently can't try out the dev branch.

img_path should only be used in the "Others" tab. It's not visible for the remaining tabs (in the code with visible=others_dir). It's created, but its event should not be able to be occur. (Of course unless there's a bug somewhere...)

I tend to avoid state, because people often stop webui, restart it and use the same browser tab as before, which does not retain state and leads to some error.

**Comment by KohakuBlueleaf** [comment]
@AlUlkesh So maybe we can try to use different/unique label name for other tabs?
and since they are invisible, it is ok to add on lot of tricky string in label name.

**Comment by KohakuBlueleaf** [comment]
> I'm afraid I don't quite understand. And I currently can't try out the dev branch.
> 
> img_path should only be used in the "Others" tab. It's not visible for the remaining tabs (in the code with visible=others_dir). It's created, but its event should not be able to be occur. (Of course unless there's a bug somewhere...)
> 
> I tend to avoid state, because people often stop webui, restart it and use the same browser tab as before, which does not retain state and leads to some error.

And it is not "used" by "non-others tab"
it is "changed" by sd-webui since they has same label name and share same value in ui-config

**Comment by AlUlkesh** [comment]
https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/commit/c61fae964ac94bc369fd0e346805e3e2885c69b4

Thank you! 😄 

When I'm back, I'll have to look into what webui is trying to do here with this change.

**Comment by picobyte** [comment]
My stablediffusion was dysfunctional in runpod, also my local (on CPU) becamedysfunctional. this extension was one that got updated. Disabling this extension made stable-diffusion_webui work again. Is what you're discussing here causing this?

**Comment by AlUlkesh** [comment]
See #195

**Comment by AlUlkesh** [comment]
I just merged the fix for #195. This should take care of all fields. So I now removed the special handling of img_path again.
