### ISSUE TITLE
why web-ui  no new tab "Image Browser"

### ISSUE THREAD

**Issue by horoabb** [AlUlkesh/stable-diffusion-webui-images-browser#19]
I install the images-browser,but webui not find 

i use stable-diffusion-webui-docker

// --listen --port 7860 --enable-insecure-extension-access

**Comment by AlUlkesh** [comment]
Did you restart webui?
Are there any error messages in the console log?

**Comment by horoabb** [comment]
yes i restart webui?

**Comment by horoabb** [comment]
yes i restart webui?   no error

**Comment by horoabb** [comment]
+ accelerate launch --num_cpu_threads_per_process=8 webui.py --listen --port 7860 --enable-insecure-extension-access
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
No module 'xformers'. Proceeding without it.
Removing empty folder: /stable-diffusion-webui/models/BSRGAN
Error loading script: images_history.py
Traceback (most recent call last):
  File "/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser/scripts/images_history.py", line 15, in <module>
    from modules.ui_common import plaintext_to_html
ModuleNotFoundError: No module named 'modules.ui_common'

LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Calculating sha256 for /stable-diffusion-webui/models/Stable-diffusion/animefull-latest.ckpt: 80df01df1bab8952d1c8842d718fc78a575a81c9968d685ca34d725ce0b4c3c5
Loading weights [80df01df1b] from /stable-diffusion-webui/models/Stable-diffusion/animefull-latest.ckpt
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0): 
Model loaded in 12.2s (0.5s create model, 11.4s load weights).
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.

**Comment by horoabb** [comment]
ＯＫ i try

**Comment by horoabb** [comment]
hi i need help

**Comment by horoabb** [comment]
Closing server running on port: 7860
Restarting UI...
Error loading script: images_history.py
Traceback (most recent call last):
  File "/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser/scripts/images_history.py", line 23, in <module>
    from send2trash import send2trash
ModuleNotFoundError: No module named 'send2trash'

Running on local URL:  http://0.0.0.0:7860

**Comment by FrameEnder** [comment]
I'm also getting 

Closing server running on port: 7861                                                                                    Restarting UI...                                                                                                        Loading booru2prompt settings                                                                                           SD-Webui API layer loaded                                                                                               Error loading script: images_history.py                                                                                 Traceback (most recent call last):                                                                                        File "F:\Stable Diffusion WebUI's\ai\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts                script_module = script_loading.load_module(scriptfile.path)                                                           File "F:\Stable Diffusion WebUI's\ai\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module           module_spec.loader.exec_module(module)                                                                                File "<frozen importlib._bootstrap_external>", line 883, in exec_module                                                 File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                            File "F:\Stable Diffusion WebUI's\ai\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\images_history.py", line 23, in <module>                                                                                     from send2trash import send2trash                                                                                   ModuleNotFoundError: No module named 'send2trash'

**Comment by AlUlkesh** [comment]
Hmm, that should get installed automatically. Make sure you are **not** running with this commandline option:
`--skip-install`

If that's not the issue, please post the whole console log, starting with venv...

**Comment by horoabb** [comment]
REPOSITORY              TAG       IMAGE ID       CREATED          SIZE
sd-auto                 test      e741022af156   38 minutes ago   5.24GB
sd-auto                 35        58023bcfc1a2   20 hours ago     5.24GB
sd-auto                 43        58023bcfc1a2   20 hours ago     5.24GB
webui-docker-download   latest    a0747df027f2   20 hours ago     62.5MB
siomiz/chrome           latest    a53ad8ffcd92   23 months ago    1.07GB
cannot import 'tank': a pool with that name already exists
use the form 'zpool import <pool | id> <newpool>' to give it a new name
Mounted .cache
Mounted LDSR
Mounted BLIP
Mounted Hypernetworks
Mounted VAE
Mounted GFPGAN
Mounted RealESRGAN
Mounted Deepdanbooru
Mounted ScuNET
Mounted .cache
Mounted StableDiffusion
Mounted embeddings
Mounted ESRGAN
Mounted config.json
Mounted SwinIR
Mounted Lora
Mounted MiDaS
Mounted ui-config.json
Mounted BSRGAN
Mounted Codeformer
Mounted extensions
+ python -u webui.py --listen --port 7860
No module 'xformers'. Proceeding without it.
Removing empty folder: /stable-diffusion-webui/models/BSRGAN
Error loading script: images_history.py
Traceback (most recent call last):
  File "/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser/scripts/images_history.py", line 23, in <module>
    from send2trash import send2trash
ModuleNotFoundError: No module named 'send2trash'

Calculating sha256 for /stable-diffusion-webui/models/Stable-diffusion/classicAnim-v1.ckpt: Checkpoint classicAnim-v1.ckpt [93d2772039] not found; loading fallback classicAnim-v1.ckpt
93d27720391c3028ad1dd897a17468b1c993e14bfadebcebd103672c2ca62ea1
Loading weights [93d2772039] from /stable-diffusion-webui/models/Stable-diffusion/classicAnim-v1.ckpt
Creating model from config: /stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0):
Model loaded in 10.1s (calculate hash: 1.7s, load weights from disk: 1.0s, create model: 0.6s, apply weights to model: 1.0s, apply half(): 0.6s, load VAE: 4.7s, move model to device: 0.3s, load textual inversion embeddings: 0.1s).
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.

**Comment by horoabb** [comment]
other extension can use image browser relodad

**Comment by FrameEnder** [comment]
> Hmm, that should get installed automatically. Make sure you are **not** running with this commandline option: `--skip-install`
> 
> If that's not the issue, please post the whole console log, starting with venv...

venv "F:\Stable Diffusion WebUI's\ai\stable-diffusion-webui\venv\Scripts\Python.exe"                                    
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]                                 
Commit hash: ea9bd9fc7409109adcd61b897abc2c8881161256                                                                   
Installing requirements for Web UI                                                                                      
loading Dreambooth reqs from F:\Stable Diffusion WebUI's\ai\stable-diffusion-webui\extensions\sd_smartprocess\requirements.txt                                                                                                                  
Checking Smart Crop requirements.                                                                                                                                                                                                                                                                                                                                       
Installing requirement for images-browser                                                                                                                                                                                                                                                                                                                               #######################################################################################################                 
Initializing Dreambooth                                                                                                 
If submitting an issue on github, please provide the below text for debugging purposes:                                                                                                                                                         
Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]                       
Dreambooth revision:                                                                                                    
SD-WebUI revision:                                                                                                                                                                                                                              
Checking Dreambooth requirements...                                                                                     
[+] bitsandbytes version 0.35.0 installed.                                                                              
[+] diffusers version 0.10.2 installed.                                                                                
[+] transformers version 4.25.1 installed.                                                                              
[ ] xformers version N/A installed.                                                                                     
[+] torch version 1.12.1+cu113 installed.                                                                               
[+] torchvision version 0.13.1+cu113 installed.                                                                                                                                                                                                 #######################################################################################################                                                                                                                                         
Installing requirements for scikit_learn                                                                                                                                                                                                        
Launching Web UI with arguments: --port 7861 --theme=dark --disable-safe-unpickle                                       
No module 'xformers'. Proceeding without it.                                                                            ==============================================================================                                          
You are running torch 1.12.1+cu113.                                                                                     
The program is tested to work with torch 1.13.1.                                                                        
To reinstall the desired version, run with commandline flag --reinstall-torch.                                         
Beware that this will cause a lot of large files to be downloaded, as well as                                          
there are reports of issues with training tab on the latest version.                                                                                                                                                                            
Use --skip-version-check commandline argument to disable this check.                                                    ==============================================================================                                          
Loading booru2prompt settings                                                                                           
SD-Webui API layer loaded                                                                                               
Error loading script: images_history.py                                                                                 
Traceback (most recent call last):                                                                                        
File "F:\Stable Diffusion WebUI's\ai\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts                
script_module = script_loading.load_module(scriptfile.path)                                                           
File "F:\Stable Diffusion WebUI's\ai\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module           
module_spec.loader.exec_module(module)                                                                                
File "<frozen importlib._bootstrap_external>", line 883, in exec_module                                                 
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                            
File "F:\Stable Diffusion WebUI's\ai\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\images_history.py", line 23, in <module>                                                                                     
from send2trash import send2trash                                                                                   
ModuleNotFoundError: No module named 'send2trash'                                                                                                                                                                                               

Loading weights [2ad79a2618] from F:\Stable Diffusion WebUI's\ai\stable-diffusion-webui\models\Stable-diffusion\grapefruitHentaiModel_grapefruitv32.safetensors                                                                                 
Creating model from config: F:\Stable Diffusion WebUI's\ai\stable-diffusion-webui\configs\v1-inference.yaml             
LatentDiffusion: Running in eps-prediction mode                                                                         
DiffusionWrapper has 859.52 M params.                                                                                   
Applying cross attention optimization (Doggettx).                                                                       
Textual inversion embeddings loaded(0):                                                                                 
Model loaded in 68.0s (load weights from disk: 1.4s, create model: 1.4s, apply weights to model: 48.4s, apply half(): 0.8s, load VAE: 0.2s, move model to device: 1.2s, load textual inversion embeddings: 14.6s).                              
Running on local URL:  http://127.0.0.1:7861                                                                                                                                                                                                    
To create a public link, set `share=True` in `launch()`.

**Comment by AlUlkesh** [comment]
That's really odd, I see this line which says it's installing what's necessary: `Installing requirement for images-browser`

As a workaround, can you manually install it?
```
cd to webui's directory
venv\Scripts\activate.bat
pip install send2trash
```

**Comment by horoabb** [comment]
i use stable-diffusion-webui-docker

**Comment by FrameEnder** [comment]
Seems manually installing it has acted as a workaround for me.

**Comment by AlUlkesh** [comment]
> i use stable-diffusion-webui-docker

I'm not familiar with docker. But if I look at this page
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs#running-inside-docker

then it should work like that:
Execute the following inside the container:
```
cd /dockerx/stable-diffusion-webui
source venv/bin/activate
python -m pip install send2trash

```

**Comment by AlUlkesh** [comment]
@horoabb Did that work for you?

**Comment by horoabb** [comment]
> @horoabb那對你有用嗎？

no
i try download python,and find to send2trash directory, copy to Image Browser

**Comment by AlUlkesh** [comment]
@horoabb I just made send2trash optional. If it cannot be installed, a regular delete is used instead. Please update the extension to the current version.
