### ISSUE TITLE
txt2img-grids search by EXIF keyword returns all images

### ISSUE THREAD

**Issue by nailz420** [AlUlkesh/stable-diffusion-webui-images-browser#191]
subject

version: [v1.3.1-RC-6-gb6af0a38](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/b6af0a3809ea869fb180633f9affcae4b199ffcf)  •  python: 3.10.10  •  torch: 2.0.0+cu118  •  xformers: N/A  •  gradio: 3.31.0  •  checkpoint: [2a4b8e14ab](https://google.com/search?q=2a4b8e14abf3b6cd873b629a1cd290ec44b89f830e536cb1783cf81fc1c7c39d)

extension info: breanch: main, version: 59547c84, date: Fri Jun 2 00:44:00 2023

**Comment by AlUlkesh** [comment]
See #195

**Comment by AlUlkesh** [comment]
@nailz420 
I just merged the fix for #195. Can you check if it also fixes this issue?

**Comment by nailz420** [comment]
Works now
