### ISSUE TITLE
Send to img2img controlnet not working

### ISSUE THREAD

**Issue by SeargeDP** [AlUlkesh/stable-diffusion-webui-images-browser#192]
The "send to txt2img controlnet" button works fine, but the "send to img2img controlnet" button seems to be doing nothing.
I've noticed this while using controlnet version 1.1.210

**Comment by AlUlkesh** [comment]
I can't reproduce this, works fine for me. Can you check if this is still the case for you? If it is, please post a full debug file, as described here: #130

**Comment by SeargeDP** [comment]
I've bisected the installed extensions I have and could pin point the culprit. It looks like the extension "Latent Couple" (https://github.com/ashen-sensored/stable-diffusion-webui-two-shot.git) causes this issue when it is installed. I tested it with only image browser, controlnet, and latent couple extensions active and it reproduced the issue.
Hope that helps, otherwise I'll capture the debug log later and send it your way.

**Comment by AlUlkesh** [comment]
Latent Couple is naming its tabs in such a way, that they conflicted with the current tab detection. So it would never find the "img2img" tab.

This update should fix that.

**Comment by SeargeDP** [comment]
I can confirm that it's now working with your latest changes.

**Comment by AlUlkesh** [comment]
Great! Thanks.
