### ISSUE TITLE
Send to controlnet does not replace image

### ISSUE THREAD

**Issue by SeargeDP** [AlUlkesh/stable-diffusion-webui-images-browser#193]
If there is already an image loaded in controlnet and I send another one from image browser, the old image does not immediately get replaced in the controlnet unit. If I manually remove the image from controlnet, the last sent image from image browser shows up (as if it was just waiting in a queue)

Repro steps:
- load image in controlnet
- from image browser, send another image to the controlnet unit
- manually remove the current image from the controlnet unit

Controlnet version 1.1.210

**Comment by AlUlkesh** [comment]
Apparently controlnet changed the name of the "remove image" functionality from "Clear" to "Remove Image".

I've updated this, should work again.

**Comment by SeargeDP** [comment]
It is working again with the latest version
