### ISSUE TITLE
Image browser refreshes after deleting a certain number of images

### ISSUE THREAD

**Issue by atmogenic** [AlUlkesh/stable-diffusion-webui-images-browser#197]
Been having this issue for ages now and i thought i wouldn't be the only one having this.

1. go to image browser (i'm using AUTOMATIC1111)
2. select any image from your images
3. start deleting them one by one
4. eventually around 5 or 6 images the UI refreshes and takes you right back to the beginning again

https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/56037304/04e0fdac-96c1-4b66-af81-33bbbd30ebdd

**Comment by AlUlkesh** [comment]
Does it happen, if you delete slowly?

**Comment by atmogenic** [comment]
> 

yes, i let it load everything up on the right side and still gets this problem

**Comment by AlUlkesh** [comment]
Can you check if this update fixes the issue for you?

**Comment by AlUlkesh** [comment]
Great! Thanks.
