### ISSUE TITLE
Deleting or moving images sometimes throws off UI

### ISSUE THREAD

**Issue by nykwil** [AlUlkesh/stable-diffusion-webui-images-browser#20]
If you delete an image or if you move an image to favorites the image you see and the image selected are out of sync. And when you get into that state clicking send to inpainting (sends another image) as moving to favorites and also deleting (ie your not deleting the image you're seeing). Also I think the UI delete the image that the next/previous page falls onto then that page just says "Error". 
I haven't figured out the exact repro steps I did it yesterday where I add a bunch of images to favorites then I went to favorite's and it was a totally different set of images (like one image off from the ones I wanted).

**Comment by jgrunik** [comment]
This bug is especially bad when it causes the wrong image to be deleted. </3

**Comment by AlUlkesh** [comment]
Yes, absolutely. I'll check if I can find what's up with that. Probably not a bad idea to turn on the recycle bin in the options for now...

**Comment by AlUlkesh** [comment]
@nykwil Well, this has never worked correctly... This should fix the moving issue.

I couldn't replicate, what you wrote about deleting, It's possible, this fix fixed that too. If not, please let me know.
