### ISSUE TITLE
send img2img  image param not send 

### ISSUE THREAD

**Issue by inewlife** [AlUlkesh/stable-diffusion-webui-images-browser#205]
version: [v1.2.1-42-gd3abbc88](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/d3abbc88f1cb96b18a6a9eb35362a4972954d9ea)  •  python: 3.10.10  •  torch: 1.13.1  •  xformers: N/A  •  gradio: 3.29.0  •  checkpoint:

**Comment by inewlife** [comment]
--gradio-queue

**Comment by AlUlkesh** [comment]
Please post a full debug file, as described here: https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/discussions/130

**Comment by Wovik253** [comment]
Same here. Here is my log
[image_browser.log](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/files/11781350/image_browser.log)

**Comment by AlUlkesh** [comment]
Are you running main a1111 or a fork?

**Comment by Wovik253** [comment]
Main

**Comment by AlUlkesh** [comment]
Are there any error messages in the javascript console?

**Comment by inewlife** [comment]
> 



> Are there any error messages in the javascript console?
> 
> And does sending to img2img from the standard PNG Info tab work?

also not work ,I find if i remove contronet extention or remove this extention , PNG Info tab work will work

**Comment by inewlife** [comment]
If I use --no-gradio-queue,PNG Info tab work
