### ISSUE TITLE
All the components on the right panel have disappeared

### ISSUE THREAD

**Issue by Jian-chan** [AlUlkesh/stable-diffusion-webui-images-browser#210]
When I first click into this panel, it does not show any picture, then i click First Page button, pictures is loaded, but the Generate Info and File Name and all the button on the right is missing

**Comment by Jian-chan** [comment]
![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/63061078/d83a90b7-4451-47a7-8306-c7f90c4e8470)

**Comment by AlUlkesh** [comment]
If you want txt2img to be always loaded at the start you can use this setting:

![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/99896447/2fc0a649-b196-4f22-a169-bb9d8655e491)

If the Generate info is missing, please post a full debug file, as described here: https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/discussions/130

**Comment by Jian-chan** [comment]
I'm so sorry, I found out that I use a wrong git repository. now, I change the repository and it's all right.
