### ISSUE TITLE
Image Browser: ImageReward is not installed, cannot be used

### ISSUE THREAD

**Issue by 1nSaneRu** [AlUlkesh/stable-diffusion-webui-images-browser#211]
![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/2229904/6c13e7bc-2321-442b-b2cf-3fa6cab6abc9)
How to fix?

**Comment by 1nSaneRu** [comment]
When I try to
`pip install image-reward`
![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/2229904/0e84f723-dfdb-44c7-8776-d3ac5ccfebb0)

**Comment by AlUlkesh** [comment]
Well looks like you have a package `blip-ci` installed that requires older versions of fairscale and timm. 

You can tell pip to ignore that by:
`pip install --force-reinstall image-reward`

However then blip or some package that depends on it might not work anymore.

**Comment by AlUlkesh** [comment]
#220
