### ISSUE TITLE
Aesthetic scoring function reports errors

### ISSUE THREAD

**Issue by klossm** [AlUlkesh/stable-diffusion-webui-images-browser#213]
I use webui 1.4

Traceback (most recent call last):
  File "L:\stable-diffusion\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "L:\stable-diffusion\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "L:\stable-diffusion\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "L:\stable-diffusion\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "L:\stable-diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "L:\stable-diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "L:\stable-diffusion\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 1081, in generate_image_reward
    image_reward_model = ImageReward.load("ImageReward-v1.0")
  File "L:\stable-diffusion\venv\lib\site-packages\ImageReward\utils.py", line 65, in load
    model_path = ImageReward_download(_MODELS[name], download_root or os.path.expanduser("~/.cache/ImageReward"))
  File "L:\stable-diffusion\venv\lib\site-packages\ImageReward\utils.py", line 41, in ImageReward_download
    hf_hub_download(repo_id="THUDM/ImageReward", filename=filename, local_dir=root)
  File "L:\stable-diffusion\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return _inner_fn  # type: ignore
  File "L:\stable-diffusion\venv\lib\site-packages\huggingface_hub\file_download.py", line 1286, in hf_hub_download
    "Cannot find the requested files in the disk cache and"
  File "L:\stable-diffusion\venv\lib\site-packages\huggingface_hub\file_download.py", line 1594, in _to_local_dir
    snapshot_path = os.path.join(storage_folder, "snapshots")
  File "L:\stable-diffusion\venv\lib\site-packages\huggingface_hub\file_download.py", line 873, in _create_symlink
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 807, in commonpath
    raise ValueError("Paths don't have the same drive")
ValueError: Paths don't have the same drive

**Comment by AlUlkesh** [comment]
I found this:
https://github.com/huggingface/huggingface_hub/pull/1437

Check your version of huggingface_hub. From the a1111 directory:

```
venv\Scripts\activate.bat
pip show huggingface_hub
```

It should be 0.15.1

**Comment by klossm** [comment]
> I found this: [huggingface/huggingface_hub#1437](https://github.com/huggingface/huggingface_hub/pull/1437)
> 
> Check your version of huggingface_hub. From the a1111 directory:
> 
> ```
> venv\Scripts\activate.bat
> pip show huggingface_hub
> ```
> 
> It should be 0.15.1

I installed huggingface_hub==0.15.1 and still reported the same wrong content.

**Comment by AlUlkesh** [comment]
> I installed huggingface_hub==0.15.1 and still reported the same wrong content.

And it is still installed? Sometimes extensions install different versions, when a1111 runs.

**Comment by klossm** [comment]
> > I installed huggingface_hub==0.15.1 and still reported the same wrong content.
> 
> And it is still installed? Sometimes extensions install different versions, when a1111 runs.

When running the error, I checked that the huggingface_hub in the venv environment is 0.15.1

**Comment by AlUlkesh** [comment]
Ok, let's get the versions of all your packages, please do a

venv\Scripts\activate.bat
pip list

**Comment by klossm** [comment]
(venv) L:\stable-diffusion>pip list
Package                      Version
---------------------------- ------------------
absl-py                      1.4.0
accelerate                   0.18.0
addict                       2.4.0
aenum                        3.1.12
aiofiles                     23.1.0
aiohttp                      3.8.4
aiosignal                    1.3.1
albumentations               1.3.1
aliyun-python-sdk-alimt      3.2.0
aliyun-python-sdk-core       2.13.10
altair                       5.0.0
antlr4-python3-runtime       4.9.3
anyio                        3.6.2
asttokens                    2.2.1
astunparse                   1.6.3
async-timeout                4.0.2
attrs                        23.1.0
audioread                    3.0.0
av                           10.0.0
backcall                     0.2.0
basicsr                      1.4.2
beautifulsoup4               4.12.2
blendmodes                   2022
blip-ci                      0.0.3
blis                         0.7.9
boltons                      23.0.0
boto3                        1.26.133
botocore                     1.29.133
Brotli                       1.0.9
cachetools                   5.3.0
catalogue                    2.0.8
certifi                      2023.5.7
cffi                         1.15.1
chardet                      4.0.0
charset-normalizer           2.0.12
clean-fid                    0.1.35
click                        8.1.3
clip                         1.0
clip-interrogator            0.5.4
color-matcher                0.5.0
colorama                     0.4.6
coloredlogs                  15.0.1
confection                   0.0.4
contourpy                    1.0.7
cryptography                 40.0.2
cssselect2                   0.7.0
cycler                       0.11.0
cymem                        2.0.7
Cython                       0.29.35
datasets                     2.11.0
ddt                          1.6.0
decorator                    4.4.2
deprecation                  2.1.0
diffusers                    0.16.0
dill                         0.3.6
diskcache                    5.6.1
dlib-bin                     19.24.1
docutils                     0.20.1
duckduckgo-search            3.7.1
dynamicprompts               0.27.0
easydict                     1.10
einops                       0.6.1
executing                    1.2.0
face-alignment               1.3.5
facexlib                     0.3.0
fairscale                    0.4.13
fastapi                      0.94.0
ffmpy                        0.3.0
filelock                     3.12.0
filterpy                     1.4.5
flatbuffers                  23.5.9
font-roboto                  0.0.1
fonts                        0.0.3
fonttools                    4.39.4
freetype-py                  2.3.0
frozenlist                   1.3.3
fsspec                       2023.5.0
ftfy                         6.1.1
future                       0.18.3
fvcore                       0.1.5.post20221221
gast                         0.4.0
gdown                        4.7.1
gfpgan                       1.3.8
gitdb                        4.0.10
GitPython                    3.1.30
google-auth                  2.18.0
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
gradio                       3.32.0
gradio_client                0.2.4
grpcio                       1.54.0
h11                          0.12.0
h2                           4.1.0
h5py                         3.8.0
hpack                        4.0.0
httpcore                     0.15.0
httpx                        0.24.1
huggingface-hub              0.15.1
humanfriendly                10.0
hyperframe                   6.0.1
idna                         2.10
ifnude                       0.0.3
image-reward                 1.4
imageio                      2.28.1
imageio-ffmpeg               0.4.7
importlib-metadata           6.6.0
inflection                   0.5.1
insightface                  0.7.3
iopath                       0.1.9
ipython                      8.6.0
jax                          0.4.9
jedi                         0.18.2
Jinja2                       3.1.2
jmespath                     0.10.0
joblib                       1.2.0
jsonmerge                    1.8.0
jsonschema                   4.17.3
keras                        2.12.0
kiwisolver                   1.4.4
kornia                       0.6.7
langcodes                    3.3.0
lark                         1.1.2
lazy_loader                  0.2
libclang                     16.0.0
librosa                      0.8.0
lightning-utilities          0.8.0
linkify-it-py                2.0.2
llvmlite                     0.40.0
lmdb                         1.4.1
lpips                        0.1.4
lxml                         4.9.2
Markdown                     3.4.3
markdown-it-py               2.2.0
MarkupSafe                   2.1.2
matplotlib                   3.7.1
matplotlib-inline            0.1.6
mdit-py-plugins              0.3.3
mdurl                        0.1.2
mediapipe                    0.10.0
memory-tempfile              2.2.3
ml-dtypes                    0.1.0
moviepy                      1.0.3
mpmath                       1.3.0
multidict                    6.0.4
multiprocess                 0.70.14
murmurhash                   1.0.9
mypy-extensions              1.0.0
natsort                      8.3.1
networkx                     3.1
numba                        0.57.0
numpy                        1.23.5
oauthlib                     3.2.2
omegaconf                    2.2.3
onnx                         1.14.0
onnxruntime                  1.15.0
onnxruntime-gpu              1.14.1
open-clip-torch              2.19.0
openai                       0.27.6
opencv-contrib-python        4.7.0.72
opencv-python                4.7.0.72
opencv-python-headless       4.7.0.72
opt-einsum                   3.3.0
orjson                       3.8.12
packaging                    23.1
pandas                       2.0.1
parso                        0.8.3
pathos                       0.3.0
pathy                        0.10.1
pickleshare                  0.7.5
piexif                       1.1.3
Pillow                       9.5.0
pip                          23.1.2
platformdirs                 3.5.1
pooch                        1.7.0
portalocker                  2.7.0
pox                          0.3.2
ppft                         1.7.6.6
preshed                      3.0.8
prettytable                  3.8.0
proglog                      0.1.10
prompt-toolkit               3.0.38
protobuf                     3.20.3
psutil                       5.9.5
pure-eval                    0.2.2
pyarrow                      12.0.1
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pycairo                      1.23.0
pycparser                    2.21
pydantic                     1.10.9
pydub                        0.25.1
PyExecJS                     1.5.1
Pygments                     2.15.1
PyMatting                    1.1.8
pyparsing                    3.0.9
pyre-extensions              0.0.29
pyreadline3                  3.4.1
pyrsistent                   0.19.3
PySocks                      1.7.1
python-dateutil              2.8.2
python-multipart             0.0.6
pytorch-lightning            1.9.4
pytz                         2023.3
pyvirtualcam                 0.10.2
PyWavelets                   1.4.1
pywin32                      306
PyYAML                       6.0
qudida                       0.0.4
realesrgan                   0.3.0
regex                        2023.5.5
rembg                        2.0.30
reportlab                    4.0.0
requests                     2.30.0
requests-oauthlib            1.3.1
resampy                      0.4.2
resize-right                 0.0.2
responses                    0.18.0
rich                         13.4.2
rlPyCairo                    0.2.0
rsa                          4.9
s3transfer                   0.6.1
safetensors                  0.3.1
scikit-image                 0.20.0
scikit-learn                 1.2.2
scipy                        1.10.1
seaborn                      0.12.1
segment-anything             1.0
segmentation-refinement      0.6
semantic-version             2.10.0
Send2Trash                   1.8.0
sentencepiece                0.1.99
setuptools                   63.2.0
six                          1.16.0
smart-open                   6.3.0
smmap                        5.0.0
sniffio                      1.3.0
socksio                      1.0.0
sounddevice                  0.4.6
soundfile                    0.12.1
soupsieve                    2.4.1
spacy                        3.5.2
spacy-legacy                 3.0.12
spacy-loggers                1.0.4
srsly                        2.4.6
stack-data                   0.6.2
starlette                    0.26.1
supervision                  0.8.0
svglib                       1.5.1
sympy                        1.12
tabulate                     0.9.0
tb-nightly                   2.14.0a20230511
tencentcloud-sdk-python      3.0.889
tensorboard                  2.12.3
tensorboard-data-server      0.7.0
tensorflow                   2.12.0
tensorflow-estimator         2.12.0
tensorflow-intel             2.12.0
tensorflow-io-gcs-filesystem 0.31.0
termcolor                    2.3.0
thinc                        8.1.10
threadpoolctl                3.1.0
tifffile                     2023.4.12
timm                         0.6.13
tinycss2                     1.2.1
tokenizers                   0.13.3
tomesd                       0.1.2
tomli                        2.0.1
toolz                        0.12.0
torch                        2.0.1+cu118
torchdiffeq                  0.2.3
torchmetrics                 0.11.4
torchsde                     0.2.5
torchvision                  0.15.2+cu118
tqdm                         4.65.0
traitlets                    5.9.0
trampoline                   0.1.2
transformers                 4.27.4
translators                  5.7.1
transparent-background       1.2.4
triton                       2.0.0
typer                        0.7.0
typing_extensions            4.5.0
typing-inspect               0.8.0
tzdata                       2023.3
uc-micro-py                  1.0.2
ultralytics                  8.0.121
urllib3                      1.26.15
uvicorn                      0.22.0
wasabi                       1.1.1
wcwidth                      0.2.6
webencodings                 0.5.1
websockets                   11.0.3
Werkzeug                     2.3.4
wheel                        0.40.0
wrapt                        1.14.1
xformers                     0.0.20
xxhash                       3.2.0
yacs                         0.1.8
yapf                         0.33.0
yarl                         1.9.2
zipp                         3.15.0

**Comment by AlUlkesh** [comment]
You are getting the exact same error as before? Including the line number?

`File "L:\stable-diffusion\venv\lib\site-packages\huggingface_hub\file_download.py", line 873, in _create_symlink`

Line 873 is not even code in Version 0.15.1 anymore.

The only explanation I could come up for that, would be if when you get the error, the old version is temporarily installed.

**Comment by klossm** [comment]
> huggingface_hub

After I restart webui a few times, I make sure that huggingface_hub is version 0.15.1 each time and there is no error. Thank you.

**Comment by AlUlkesh** [comment]
Ah, good. Let me know if it should happen again.
