### ISSUE TITLE
Make ImageReward optional

### ISSUE THREAD

**Issue by AlUlkesh** [AlUlkesh/stable-diffusion-webui-images-browser#219]
It seems ImageReward runs into dependency issues from time to time. Because of this and since not everyone uses it, it should be optional.

**Comment by vladmandic** [comment]
may not be sufficient - see <https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/issues/216#issuecomment-1648724231>

**Comment by AlUlkesh** [comment]
#220
