### ISSUE TITLE
[Bug] Sidebar items aren't hidden/removed even though option is set in settings

### ISSUE THREAD

**Issue by robonxt** [AlUlkesh/stable-diffusion-webui-images-browser#229]
First off, thank you for making this extension! It's really helpful to manage and look for previous generations!

Per the title, I'm having issues where I set several items in the "hidden components" settings, however certain items are not being removed from the UI.

My settings in the `config.json` file:

```
"image_browser_hidden_components": [
    "Sort by",
    "Filename keyword search",
    "Ranking Filter",
    "Aesthestic Score",
    "Open Folder",
    "Copy to directory",
    "Ranking Bar"
],
```
The result:
![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/8854735/340d6ee2-3e67-4631-a6ef-65cdfbb4948e)

**Comment by AlUlkesh** [comment]
Thanks!

I looked at the code... and I think this never worked. Either that or there was a fundamental change in Gradio, that affected this.

Currently only the elements that get hidden/shown depending on if you are on the thumbnail overview or the image view (like delete) get hidden.

I'll try to implement a version that works for the remaining fields.

**Comment by robonxt** [comment]
It used to work, prior to 2 weeks ago. My gradio is still on the default 3.32.0 (it hasn't changed for a while), so I don't think it's gradio issue, unless something changed in the webUI itself.

**Comment by AlUlkesh** [comment]
That's great, that you remembered it worked 2 weeks ago for you, still.

With this timeframe I was able to pinpoint the issue. It was a completely unrelated change, that was supposed to be purely visual.

Does the new commit work for you?

**Comment by robonxt** [comment]
Yep! It's working now. Thanks for the quick fix!
