### ISSUE TITLE
images not displaying properly

### ISSUE THREAD

**Issue by Kapowpenguin1** [AlUlkesh/stable-diffusion-webui-images-browser#230]
since commit a3aeb93, image browser displays images like this 
![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/12951389/fd7d6cd3-33a7-48e6-94fd-cbe6f2b3ac60)
instead of this 
![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/12951389/55b4c7a8-9352-4ef1-bbb7-fc1115eb2942)
is this supposed to happen? and if not, is there something i should do to fix it?
i'm running on webui commit [22bcc7be](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81), but it seems happen in the latest webui commit too

**Comment by AlUlkesh** [comment]
Hmm, doesn't happen for me.

Which Gradio version are you running?

And how is that setting set for you:

![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/99896447/cd11d5eb-a404-4f87-8e48-ed9a98ddb605)

**Comment by Kapowpenguin1** [comment]
i'm on 3.32, so i'm guessing that toggling it wouldn't work either way [i tried anyways, and as expected, it doesn't seem to do anything]. i'm not sure how to upgrade gradio tho

**Comment by AlUlkesh** [comment]
Yes, 3.32 with the box not ticked should work.

Can you post a complete debug log (from starting a1111 until the error happens), as described here: #130

**Comment by Kapowpenguin1** [comment]
[image_browser.log](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/files/12444726/image_browser.log)

**Comment by AlUlkesh** [comment]
Are there no javascript logs? Did you press the Get Javascript Logs button?

**Comment by Kapowpenguin1** [comment]
i'm not seeing any useful javascript logs. pressing "Get Javascript Logs" just populates the text box with
2023-08-26-07-12-33 image_browser.js: image_browser_turnpage:start
2023-08-26-07-12-33 image_browser.js: image_browser_turnpage:end
and creates a log file for image_browser.py

**Comment by Kapowpenguin1** [comment]
this still seems to happen even when i force the webui to use a newer gradio version [3.41.2] by changing the "requirements" files. but for the latest webui commit and gradio 3.32.0, the images still don't display properly, but differently
https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/12951389/327b8141-ad50-4a40-9f3b-65ce9a20d38a
first example is webui commit c9c8485 with gradio 3.32.0, second example is webui commit c9c8485 with gradio 3.41.2, both examples of "Use automatic height" checked

**Comment by AlUlkesh** [comment]
Can't see anything odd in the log. I take it that is only set from your recent testing, as it should be off for your Gradio version:
`    "image_browser_height_auto": true,`

I now tried out several versions and branches of a1111, but can't replicate it.

You can try to temporarily disable every other extension, to see if some interaction could be the problem.

**Comment by Kapowpenguin1** [comment]
i had a fresh, test install of the webui i used as a reference, and image browser on that one worked fine, so i started messing around with my bugged install and reinstalling stuff. 
i installed a newer version of torch [from 1.13.1 to 2.0.1] and a newer version of xformers through commandline flags, then uninstalled and reinstalled gradio through pip. 
i'm not sure which of those changes made a difference, but image browser images seem to be displaying... relatively properly again. the gallery goes further than i'm used to, but i'm assuming that's intentional
for reference, gallery previously
![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/12951389/8fb63f25-2359-403d-bf4d-2f664d58dce6)
vs gallery now
![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/12951389/9255252d-d2b6-4d49-8845-4ac11f9cdd7e)

**Comment by AlUlkesh** [comment]
Thanks for letting me know in detail. That always helps if something similar comes up.

BTW... which model/lora are you using in your screenshots?

**Comment by Kapowpenguin1** [comment]
those generations specifically were with abyss orange mix 2_hard [0fc198c4908e98d7aae2a76bd78fa004e9c21cb0be7582e36008b4941169f18e], controlnet with posex and openpose, and some prompt experimentation

btw, i'm having another issue where clicking on an image doesn't open it up like it should, just stays in grid view. any ideas on why this is?

**Comment by AlUlkesh** [comment]
Thanks 😄 

> btw, i'm having another issue where clicking on an image doesn't open it up like it should, just stays in grid view. any ideas on why this is?

Yes, that's the effect you get when you have the automatic height set with Gradio < 3.39. Check that setting again.

**Comment by Kapowpenguin1** [comment]
i updated gradio, and that seems to have fixed the image preview issue, but toggling automatic height actually ended up causing another issue. this is what happens with automatic height enabled
![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/12951389/5b42601d-1916-4c7a-b8e7-c5a8499b768f)
and this is when it's disabled
![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/12951389/fac29c14-dada-4170-a185-1df4599a09d7)
automatic height seems to make the margins a lot bigger than they should be

**Comment by AlUlkesh** [comment]
> i actually just realized that, as long as i don't use automatic height, i don't need to update gradio

Yes, exactly, sorry if I wasn't clear on that.

btw the a1111 dev branch is on 3.39, so it shouldn't take too long for the main branch to follow.

I think the effect you saw with the "margins" is because the usable frame is larger with auto height and so the "center" is lower. I don't think that's easily adjustable, since the way the Gradio gallery works, all the thumbnails from the thumbnail view are still there, just hidden.

**Comment by Kapowpenguin1** [comment]
good to know- anyways, appreciate you helping me out again-
