### ISSUE TITLE
=> Text creates infinite spinning Gradio block in "Override settings"

### ISSUE THREAD

**Issue by tranzmatt** [AlUlkesh/stable-diffusion-webui-images-browser#231]
When browsing my images and clicking the "=> Text" button, everything populates, but the "Override Settings" lists the VAE I selected, but also has the infamous infinite gradio spinning.  I can delete the VAE listed, but the gradio keeps spinning, which will dork things because it seems to create some sort of blocking thread.  I'm using commit b8f6e05d.

![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/867466/894c105e-15e4-422a-820d-3ce6ccfcb7c4)

**Comment by AlUlkesh** [comment]
Where in the image browser tab do you see a "=> Text" button?
