### ISSUE TITLE
issues caused by black images

### ISSUE THREAD

**Issue by QinCaii** [AlUlkesh/stable-diffusion-webui-images-browser#232]
Deleting a black image will cause its previous image to be deleted (that is, the next image in the image browser)
If this is not an accidental error, then it should be easy to replicate in most environments.

**Comment by AlUlkesh** [comment]
What do you mean exactly with "black image"? Do you have an example?

**Comment by QinCaii** [comment]
> What do you mean exactly with "black image"? Do you have an example?

Why? Black images are inevitable like this
![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/49438338/9732de2a-c4fe-4d18-adc2-141fb6bb1851)
By the way, when you click on an image in the image browser that prev one of the black image, the generation info and file name displays exactly that black image. Unless using directional keys
I can give you an original image, which file is usually very small. You cannot guarantee that such things will not appear in the image browser.
![07054-833412015-masterpiece, best quality, under the deep sea, high res, extra quality, bubbles, no humans, deep water, deep dark, pov, abyss](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/49438338/0d6849fa-03ae-4f13-84e8-bfd0a17edb26)

**Comment by AlUlkesh** [comment]
I just tried it with the image you provided, but there were no problems here.

What version of a1111 are you using?

And what version of this extension are you using? Is it the current one? You can check this by taking a look at `extensions/stable-diffusion-webui-images-browser/scripts/image_browser.py`

It needs to contain this code:

https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/blob/b8f6e05d1d23b3d0d17b0a9cfbf824bf4a1f98e9/scripts/image_browser.py#L1182

If it does you have the current version. If it does not, please update.

**Comment by QinCaii** [comment]
> I just tried it with the image you provided, but there were no problems here.
> 
> What version of a1111 are you using?
> 
> And what version of this extension are you using? Is it the current one? You can check this by taking a look at `extensions/stable-diffusion-webui-images-browser/scripts/image_browser.py`
> 
> It needs to contain this code:
> 
> https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/blob/b8f6e05d1d23b3d0d17b0a9cfbf824bf4a1f98e9/scripts/image_browser.py#L1182
> 
> If it does you have the current version. If it does not, please update.

Oh, obviously I am in the old version, the new code is working well
