### ISSUE TITLE
How to transfer images to new install and keep rankings?

### ISSUE THREAD

**Issue by local306** [AlUlkesh/stable-diffusion-webui-images-browser#240]
I had to move computers and I'm slowly migrating my images over. Is there way to copy over my rankings from my last setup to the new install?

**Comment by AlUlkesh** [comment]
The easiest way would be to copy the old database file `wib.sqlite3` to the new location.

If you have the exact same path names, as on your old system, you should already be set after a a1111 restart.

If the path names differ, after you restart a1111, head to `Image-Browser - Maintenance` and hit `Reapply ranking after moving files`.

What should now happen is, that all currently configured directories are scanned and the same files in the database searched, even if their path differs. Then their ranking info is adjusted.

If that doesn't work, let me know, there's yet another way.

**Comment by local306** [comment]
Thanks @AlUlkesh! Worked like a charm 😊
