### ISSUE TITLE
[Feature Request] Add functionality to load models used in image generation when sending to txt2img/img2img

### ISSUE THREAD

**Issue by tdtrumble** [AlUlkesh/stable-diffusion-webui-images-browser#251]
It would be helpful if the tool was capable of loading models used in image generation (from png metadata) when sending to txt2img/img2img. Both the main checkpoint and any other used, if possible, such as the hires checkpoint if it was different. It would probably be good to control this function using a new setting, and maybe have it disabled by default.

**Comment by AlUlkesh** [comment]
Hmm, it should already do that, unless you have it globally deactivated. Check your settings under "Infotext", esp. "Disregard checkpoint information from pasted infotext" should not be activated.
