### ISSUE TITLE
Forge issues

### ISSUE THREAD

**Issue by bl4ckfyr3** [AlUlkesh/stable-diffusion-webui-images-browser#258]
Doesnt work on forge, the images section is completely greyed out and not accessible.

**Comment by AlUlkesh** [comment]
Yes, something in Forge broke it again... I'll go check.

**Comment by AlUlkesh** [comment]
Ok, please check if this commit solves the issue for you.

**Comment by bl4ckfyr3** [comment]
Thanks, @AlUlkesh , the last commit solves it!

**Comment by supersonic13** [comment]
hi - not sure if it makes sense, but I see a loop of “queue/join” calls (in the chrome dev tools -> network monitor) when the extension is installed and goes away when I delete the extension. The CPU usage goes up and the UI gets laggy.

**Comment by AlUlkesh** [comment]
Hmm, yes, I see it too. Also the JS console keeps generating warnings. Unfortunately they point deep into Gradio code. I'm not yet sure how I can tackle this.

**Comment by supersonic13** [comment]
Thanks for looking into it. Thought the new Gradio version had something to do with it.

**Comment by AlUlkesh** [comment]
Ok, this fixes it for me. Can you also check?

**Comment by supersonic13** [comment]
that seems to have fixed the issue for me too ! thank you very much !
