### ISSUE TITLE
[Feature request] Jump to top of page

### ISSUE THREAD

**Issue by Raph404** [AlUlkesh/stable-diffusion-webui-images-browser#261]
Couldn't see an option for it, but it would be nice if when you click the First / Prev / Next / End page buttons, it would jump to the top of the list, rather than staying at the same position.

I find myself scrolling through a page, clicking Next, and having to scroll back up just to down down the next list

**Comment by AlUlkesh** [comment]
Did you try this option? This displays the thumbnails without a scrollbar, which I think is the root of this issue.

![image](https://github.com/user-attachments/assets/583690b4-a97b-4df5-8075-625c3ec5c52f)

**Comment by Raph404** [comment]
Gave it a try, but then it just scrolls the entire page, which means I have to scroll back up to see the page buttons

**Comment by AlUlkesh** [comment]
Ok, I'll look into it.

**Comment by AlUlkesh** [comment]
This commit should fix that. Can you check, if it works as expected now?

**Comment by Raph404** [comment]
That's perfect! Thank you so much
