### ISSUE TITLE
Wrong interaction between delete function and left/right keys

### ISSUE THREAD

**Issue by AlUlkesh** [AlUlkesh/stable-diffusion-webui-images-browser#29]
@Woisek
> When browsing the gallery and you use the "delete next" option and enter, say 2, and hit delete, it deletes the two images.
BUT: If you then use the arrow keys to navigate left and right, it displays the two deleted images, altough there are not visible in the image bar on the bottom. If one then hits delete again on a supposed to be deleted image again, it deletes the next one.
This is potential dangerous, as one could delete images that shouldn't or wanted to be deleted.

Yes, I was able to replicate that. Looking at the code, I think this is the issue:

- The javascript function `image_browser_delete` does in fact not delete or remove anything. It simply hides the displayed thumbnails from the bottom row. The intention probably being, that if you can't click on them anymore, they are "out of the way".
- However using left/right keys still selects them, since they are still there, just not visible.

The problem I have with this is that left/right handling seems to be done by gradio in this case. And while I could remove the files from the list on delete in the python function, I think this would bring you back to the overview gallery view.

I'll have to think about this one...

**Comment by AlUlkesh** [comment]
@Woisek
Until I can come up with something better, I changed it now so that if a delete happens and you press left key, the page refreshes instead. Not the best solution, but better than deleting the wrong image I think...

**Comment by Woisek** [comment]
@AlUlkesh 
OK, I see what it does. But is it possible, to refresh only if an image was actually deleted? Because "left scrolling" is now impossible. :/

And, have you had time to think about my idea regarding the self-defined "move to folder" ... ?

**Comment by EllangoK** [comment]
Hey @AlUlkesh, I have also noticed this issue and tried a bunch to come up with a solution. I may have a solution (I am still working on it, I think I found a way to disable gradios left and right arrow and do everything manually)

But, a better way to do it as workaround imo, and which is what I currently did as like a manual patch, is just call a refresh everytime I delete. I think its better tbh then just doing it with the left arrow and more consistent at least. 
Would also be simpler as you just modify the delete button callback instead of adding that checkbox and everything.

**Comment by AlUlkesh** [comment]
@Woisek 
... for me it only does it when an image was deleted. Did you restart everything?

@EllangoK 
My thinking was that if you use it to delete you might want to delete one and then go two right to delete the next one and go looking for more. A full refresh might be too disruptive here.

But certainly, this is a band-aid fix at best. If you found out how to trick gradio, that would be great.

Sometimes I think forcing gradio into doing what it should, takes up most of the time here...

**Comment by Woisek** [comment]
@AlUlkesh 
> ... for me it only does it when an image was deleted. Did you restart everything?

I restarted several times while working ... but strangely enough, now it seems to work like you said ... :/

> No, didn't get around yet to the move to folder idea.

OK, just wanted to remind you. :)
Do you have something different where I could help?

**Comment by AlUlkesh** [comment]
See #94
