### ISSUE TITLE
In Settings -> Image Browser these two settings are totally ignored. reload A1111 does not help.

### ISSUE THREAD

**Issue by axemaster** [AlUlkesh/stable-diffusion-webui-images-browser#31]
In Settings -> Image Browser these two settings are totally ignored. reload A1111 does not help.

Image Browser always used the default values no matter what I set here. I would love to change these.

Number of columns on the page
Number of rows on the page

**Comment by AlUlkesh** [comment]
This works for me. I can change settings and do a Reload UI and the new numbers are used.

Did this get properly saved in your setting? Can you check your `config.json`?

**Comment by axemaster** [comment]
"image_browser_page_columns": 8.0,
    "image_browser_page_rows": 2.0,

It is working now. I had to kill python and run A1111 again. I had tried to apply the new setting by doing "Apply and reload UI" in the extensions tab, and that did not work. ¯\_(ツ)_/¯

Please close issue, thanks.
