### ISSUE TITLE
FEATURE REQUEST: Mac: CTRL + arrow <- -> binding conflict with Mac desktop, make configurable

### ISSUE THREAD

**Issue by axemaster** [AlUlkesh/stable-diffusion-webui-images-browser#32]
FEATURE REQUEST: Mac: CTRL + arrow <- -> binding conflict with Mac desktop, make configurable

Mac already uses these key combinations to navigate application Windows. Please make the key bindings configurable.
As of now I can't use them in Image Browser.

PS key to jump out of the image being viewed back up to the images summary pane would be nice. If I get time I might make a PR for that.

Cheers!

**Comment by AlUlkesh** [comment]
I put in new settings:
![image](https://user-images.githubusercontent.com/99896447/218249688-ded0eb3a-7929-4b55-bec9-0037c8048783.png)

ALT + arrow is already used by the browser. I hope one of these is not already used on a Mac.

> key to jump out of the image being viewed back up to the images summary pane would be nice

Have you tried pressing R? I think that should do that.

**Comment by axemaster** [comment]
Thank you for new setting. These bindings are available on the Mac. At least I am not aware of anything that intercepts them. I set updated the installed extension and changed this in Settings tab.
    "image_browser_mod_shift": true,
and restarted A1111 but it not change anything.

But.. SHIFT+arrow (or CTRL+SHIFT+ARROW) do not change page. When look at a single image it does move to the next/prev image, with or without the SHIFT. But no effect when viewing a page.

Perhaps an option to change to [HJKL](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlKpqi4cddHGLpG95H9OpIuqxUgjedIqIGgg&usqp=CAU) VI-style navigation?

Pressing R has no effect at all, either when looking at a single image or when looking at a page of images.

When viewing a single image, ESC exits back to the page. But if I click the image (which zooms it near-full screen) pressing escape simply un-zooms back to the smaller version. Pressing ESC again does not get back the page. So there seems to be no way to exit a zoomed image and get back to the page via keyboard. It would be nice of the second ESC would go back to the page of images.

I am using Chrome on a Mac M1. By any chance do you have access to one to test upon?

(I also tried Safari. Same behaviors, although Safari is noticeably slow to load a page of images. Which is one of the many reasons I use Chrome on Mac...)

I looked at the log entry and the second check here appears to be for SHIFT+ARROW but is also looks for ctrlKey. This looks like a copy-paste. In any case neither option is working for me although it looks like CTRL+SHIFT should work. ¯\_(ツ)_/¯ I code in Scala so I am guessing here.

`if (mod_keys.indexOf("C") !== -1 && mod_keys.indexOf("S") !== -1) {
        if (event.ctrlKey && event.shiftKey) {
            modifiers_pressed = true;
        }
    } else if (mod_keys.indexOf("S") !== -1) {
        if (!event.ctrlKey && event.shiftKey) {
            modifiers_pressed = true;
}`

**Comment by AlUlkesh** [comment]
Are you perhaps in a text entry field when you do this? If so, click somewhere else first.

**Comment by axemaster** [comment]
> Are you perhaps in a text entry field when you do this? If so, click somewhere else first.

I had already thought of this and tested it. It does not matter where the focus is (or isn't). Nothing makes it work.
I don't know to debug this and step through the code while it's (not) happening. Is there some kind of logging I can collect from the extension or the browser?

**Comment by axemaster** [comment]
In the dev tool Console. Does this mean anything?

```
8image_browser.js?1676149079.8373878:224 Uncaught TypeError: Cannot read properties of undefined (reading 'nodeName')
    at HTMLDocument.<anonymous> (image_browser.js?1676149079.8373878:224:16)
(anonymous) @ image_browser.js?1676149079.8373878:224
```

**Comment by AlUlkesh** [comment]
Unfortunately I don't have access to a Mac, that would make this easier.

The first thing to check would be the javascript console. In most browseers you can access this with Inspect from the context menu and then click on console. Press some of the keys that should work and check if there are any error messages.

(You can ignore the one about xt.data)

**Comment by axemaster** [comment]
See message above. The number  next to that console message goes up by one every time I press a key.  Any key, Including the arrows, all letter and numbers, and modifier keys like SHIFT.

**Comment by AlUlkesh** [comment]
Can you debug what happens at line 224, which seems to have a problem? Maybe we can see what's going on then:
![image](https://user-images.githubusercontent.com/99896447/218286469-408c9713-c767-4c0e-8f1c-88af448ba66e.png)

**Comment by axemaster** [comment]
How do I do that? I don't know JS or it's tools I am a senior level developer in other languages. Java/Scala/C++... so I do know how to debug, generally speaking.

**Comment by axemaster** [comment]
I think I found the debugger by clicking on the line number in the log. Are those supposed to be undefined at line 224?

```
Local
this:document
event:KeyboardEvent {isTrusted: true, key: 'ArrowRight', code: 'ArrowRight', location: 0, ctrlKey: false, …}
mod_keys:undefined
modifiers_pressed:undefined
tabname:undefined
target:undefined
Script
Window
Global
```

**Comment by axemaster** [comment]
Unfortunately I cannot catch it on SHIFT-ARROW because it stops on the breakpoint for SHIFT and then I have to continue execution and click back to the app windows but I can't do  that without releasing shift

```
Local
this:document
event:KeyboardEvent {isTrusted: true, key: 'Shift', code: 'ShiftLeft', location: 1, ctrlKey: false, …}
mod_keys:undefined
modifiers_pressed:undefined
tabname:undefined
target:undefined

```

**Comment by AlUlkesh** [comment]
Well, I think I found the issue. Apparently event.originalTarget and event.explicitOriginalTarget are not supported by all browser versions, so you get undefined. Now to find a solution...

**Comment by AlUlkesh** [comment]
Hi @EllangoK, this apparently only works in firefox, event.originalTarget and event.explicitOriginalTarget are not available in chrome:
https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/blob/e13a0bd7757802a9d352502407e786d857b317d7/javascript/image_browser.js#L223

Do you perhaps have an idea on how to make this work with other browsers?

**Comment by axemaster** [comment]
> Do you perhaps have an idea on how to make this work with other browsers?

Yikes, I'm sorry. I wish I did. I am a back end big data software developer so if it's processing 4TB on a 2000 server hadoop or Spark cluster then I'm your man. UI stuff I have no idea. But, I will try this in Firefox and see if that's a viable work around. :). Thanks for letting me know.

**Comment by axemaster** [comment]
I'll install firefox and let you know if that worked for me.

**Comment by axemaster** [comment]
It works in Firefox, so that will be my work around. But if the HJKL style navigation was an option I think that would be more portable.  Or just the arrow (cursor) keys with no modifiers. They don't seem to be doing anything else on that screen.

**Comment by EllangoK** [comment]
@AlUlkesh Sorry about that, I willl try to figure something out, but it'll probably be a bit more confusing.

To state the perhaps real issue, is that normally we would just use `event.target` and that would work perfectly. But I think because of Gradio Shadow DOM (heavy on the I think) the `event.target` is this `target: <gradio-app control_page_title="true" style="height: 42px;">`. Normally it would be of type input or textarea when typing in one.

This is the full event object note that the src and targets are both gradio-apps and not the textarea like originalTarget show.
![image](https://user-images.githubusercontent.com/23466035/218289141-769bbc67-78f3-435e-ae97-6d1fb58603cd.png)

There still probably is a way though, im looking into it rn.

**Comment by EllangoK** [comment]
also @axemaster imo hjkl would be confusing definetly for the average user. Most people who use the webui do not have programming experience and those who do probably have still probably not used vim (I have btw). It would also just be h and l not the whole mapping so I just think it wouldn't correlate well.

Also for the arrow keys would conflict then as when you click into the gallery going between the neighboring image would cause you to switch pages as well.

I think I already have found somewhat of a fix so it should be fine soon anyways.

**Comment by axemaster** [comment]
> also @axemaster imo hjkl would be confusing definetly for the average user. Most people who use the webui do not have programming experience and those who do probably have still probably not used vim (I have btw). 

This is true.

> I think I already have found somewhat of a fix so it should be fine soon anyways.

Cool! I'll be sure to test it when it's checked in.

**Comment by EllangoK** [comment]
The pr above should fix it.

And also I did try a bit to get in general configurable keybindings, so that it could be up to you, but the problem is keyboard handling is through the js code not python where most of the real code is. So its hard to like say modify it from settings as the settings are set through a python handler. The settings to change change the modifiers is already very messy because gradio doesn't really support it and in general keyboard handling directly.

**Comment by AlUlkesh** [comment]
@EllangoK Great, thanks for the quick help! :smiley:

I was surprised to find out, that in this day and age there are still differences in the major browsers that can actually break code.

But yeah, the root of the problem is, that gradio is not as configurable as we'd need it to be.

**Comment by axemaster** [comment]
Test on Mac M1 Chrome. It is fixed. Thanks very much.
