### ISSUE TITLE
show_image_info: IndexError: list index out of range

### ISSUE THREAD

**Issue by AlUlkesh** [AlUlkesh/stable-diffusion-webui-images-browser#34]
@axemaster
```
Start UI. Get this message every time on Mac M1.

Traceback (most recent call last):
File "/Users/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
output = await app.get_blocks().process_api(
File "/Users/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
result = await self.call_function(
File "/Users/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 833, in call_function
prediction = await anyio.to_thread.run_sync(
File "/Users/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
return await get_asynclib().run_sync_in_worker_thread(
File "/Users/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
return await future
File "/Users/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
result = context.run(func, *args)
File "/Users/user/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser/scripts/image_browser.py", line 478, in show_image_info
file = filenames[int(num) + int((page_index - 1) * num_of_imgs_per_page)]
IndexError: list index out of range
```

**Comment by AlUlkesh** [comment]
@axemaster
The only way I was able to reproduce this, was if I stopped webui, didn't close the browser window and restarted webui.
In that case some info is not available anymore and needs to get refreshed.

This latest commit does that. Let me know, if that solves the issue.

**Comment by VeMeth** [comment]
I still got the same error when I browse over an image in the image browser or try to delete an image.

**Comment by gottahavekaia** [comment]
> @axemaster The only way I was able to reproduce this, was if I stopped webui, didn't close the browser window and restarted webui. In that case some info is not available anymore and needs to get refreshed.
> 
> This latest commit does that. Let me know, if that solves the issue.

It didn't. Still the same error. I hope you can solve it!

**Comment by Woisek** [comment]
I also experience an error:
`Traceback (most recent call last):
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 935, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range`

**Comment by AlUlkesh** [comment]
@Woisek That's a different error, since it happens in gradio. I moved it here: #35

**Comment by AlUlkesh** [comment]
@VeMeth , @gottahavekaia 

1. What operating system and browser are you using?
2. The latest commit has the first version of some debugging info, can you please activate it in the setting, close the browser window, restart webui, try again and then post the whole console log?

![image](https://user-images.githubusercontent.com/99896447/218558155-b104de75-4c74-4f45-830b-514049f5161c.png)

**Comment by AlUlkesh** [comment]
I probably found it. When I did the previous commit, apparently one file was not uploaded. That's why it worked for me. Can you try the latest commit?

**Comment by Woisek** [comment]
> @Woisek That's a different error, since it happens in gradio. I moved it here: #35

This error happens everytime after I do a update of the extension and click "Apply and restart UI". The UI is then not really working anymore, everywhere is "error" displayed. I have to restart the UI again, then it works again.
Any idea what this could be?

**Comment by AlUlkesh** [comment]
@Woisek I just ran this through debug. After pressing "Apply and restart UI", those two actions are executed concurrently. So the reload-ui probably still get at leasts parts of the old extension version. Seems like a bug on the webui side to me.

**Comment by Woisek** [comment]
@AlUlkesh 
Thanks for this evaluation of what is happening ...
I guess then, somebody should tell someone responsible for this ... ?! :)

**Comment by gottahavekaia** [comment]
> @Woisek I just ran this through debug. After pressing "Apply and restart UI", those two actions are executed concurrently. So the reload-ui probably still get at leasts parts of the old extension version. Seems like a bug on the webui side to me.

It's working again! Just updated it and everything is back to normal.

**Comment by gottahavekaia** [comment]
> I probably found it. When I did the previous commit, apparently one file was not uploaded. That's why it worked for me. Can you try the latest commit?

It's working again! Just updated it and everything is back to normal.

**Comment by Loadus** [comment]
Latest commit fixes the issue on my end as well. GJ!

**Comment by AlUlkesh** [comment]
Latest commit seems to have solved the issue. I'll close this. If anyone still has problems, please make a new issue.

**Comment by axemaster** [comment]
> > @axemaster The only way I was able to reproduce this, was if I stopped webui, didn't close the browser window and restarted webui. In that case some info is not available anymore and needs to get refreshed.
> > This latest commit does that. Let me know, if that solves the issue.
> 
> It didn't. Still the same error. I hope you can solve it!

I am no longer getting the error. But, yes I often kill A1111 and do not refresh browser.

(( too much information section ))

because doing the latter loses too many values in the UI, and on Mac M1 image generation never releases memory after processing (bug!)  so the process gets huge and very slow. It is necessary to kill it often. I wish there was an option for it to release and reload SD after every batch. I think to do this they would need to separate the UI python process and imaging engine process, otherwise they break gradio etc.  ¯\_(ツ)_/¯
