### ISSUE TITLE
Gradio: tuple index out of range

### ISSUE THREAD

**Issue by AlUlkesh** [AlUlkesh/stable-diffusion-webui-images-browser#35]
@Woisek
> I also experience an error:

`Traceback (most recent call last): File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict output = await app.get_blocks().process_api( File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1018, in process_api data = self.postprocess_data(fn_index, result["prediction"], state) File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 935, in postprocess_data if predictions[i] is components._Keywords.FINISHED_ITERATING: IndexError: tuple index out of range`

**Comment by AlUlkesh** [comment]
@Woisek: What exactly were you doing, before this error appeared?

**Comment by Loadus** [comment]
Also experiencing this, happens when I select an image (to see the image info)

`Traceback (most recent call last):
  File "G:\ai\webui\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\ai\webui\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "G:\ai\webui\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range`

**Comment by AlUlkesh** [comment]
@Loadus That's the other issue, which I think is different (#34). Anyway, do you have the latest version of this extension running?

**Comment by PeterTemps** [comment]
`Traceback (most recent call last):
  File "/home/piotr/VsCode/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/piotr/VsCode/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/piotr/VsCode/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range
`
Error in Latest update

**Comment by PeterTemps** [comment]
Also get this in the console: 

`cache_exif: 0/2443 cache_aes: 0/2443 0.0 seconds`

**Comment by AlUlkesh** [comment]
I probably found it. When I did the previous commit, apparently one file was not uploaded. That's why it worked for me. Can you try the latest commit?

**Comment by Woisek** [comment]
> @Woisek: What exactly were you doing, before this error appeared?

I think I switched to the image browser and selected an image. Instead of the "generate info" and "file name" "error" appeared.

**Comment by Loadus** [comment]
> @Loadus That's the other issue, which I think is different (#34). Anyway, do you have the latest version of this extension running?

Ah, it might be that bug, yes. I should have the latest version, 'git pull' gives 'already up to date.'

**Comment by AlUlkesh** [comment]
Latest commit seems to have solved the issue. I'll close this. If anyone still has problems, please make a new issue.
