### ISSUE TITLE
Error when using send to img2img

### ISSUE THREAD

**Issue by trihardseven** [AlUlkesh/stable-diffusion-webui-images-browser#37]
When using send to img2img/inpaint I get the following error:

Traceback (most recent call last):
  File "N:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "N:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "N:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "N:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "N:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "N:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "N:\AI\stable-diffusion-webui\modules\generation_parameters_copypaste.py", line 155, in send_image_and_dimensions
    img = image_from_url_text(x)
  File "N:\AI\stable-diffusion-webui\modules\generation_parameters_copypaste.py", line 72, in image_from_url_text
    filedata = base64.decodebytes(filedata.encode('utf-8'))
  File "C:\Users\Rance\AppData\Local\Programs\Python\Python310\lib\base64.py", line 562, in decodebytes
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

I'm on the latest version of auto. It used to work last week when I tried it.

**Comment by trihardseven** [comment]
![nodebug](https://user-images.githubusercontent.com/54422205/219064950-7fc5c34c-97f0-4f96-bfb7-fed73202127f.PNG)
Can't really find that option. I turned on show warnings in console though not sure if thats it.

venv "N:\AI\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39
Installing requirements for Web UI
Installing requirement for sd-webui-controlnet


#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 43ae9d55531004f1dedaea7ac2443e9b16739913
SD-WebUI revision: 3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.

#######################################################################################################


Launching Web UI with arguments: --xformers --no-half-vae
==============================================================================
You are running torch 1.12.1+cu113.
The program is tested to work with torch 1.13.1.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
=================================================================================
You are running xformers 0.0.14.dev.
The program is tested to work with xformers 0.0.16rc425.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
[AddNet] Updating model hashes...
100%|██████████████████████████████████████████████████████████████████████████████| 195/195 [00:00<00:00, 6088.20it/s]
[AddNet] Updating model hashes...
100%|█████████████████████████████████████████████████████████████████████████████| 195/195 [00:00<00:00, 24354.26it/s]
SD-Webui API layer loaded
Loading weights [6e350084a6] from N:\AI\stable-diffusion-webui\models\Stable-diffusion\7th_anime_3.1_A.ckpt
Creating model from config: N:\AI\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: N:\AI\stable-diffusion-webui\models\VAE\kl-f8-anime2.ckpt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(1): 001glitch-core
Model loaded in 23.1s (load weights from disk: 9.4s, create model: 0.4s, apply weights to model: 1.0s, apply half(): 0.8s, load VAE: 2.4s, move model to device: 1.0s, load textual inversion embeddings: 1.9s).
N:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Slider, please remove them: {'min': 0, 'max': 500}
  warnings.warn(
N:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'equal_height': True}
  warnings.warn(
N:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Number, please remove them: {'max': 12, 'min': 1}
  warnings.warn(
N:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Number, please remove them: {'min': 10, 'max': 200}
  warnings.warn(
[tag-editor] Settings has been read from config.json
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Comment by AlUlkesh** [comment]
> Can't really find that option. I turned on show warnings in console though not sure if thats it.

It's in Settings - Image Browser - Print debug logs to the console

It will report a lot more.

**Comment by AlUlkesh** [comment]
... and please run until the error appears.

**Comment by trihardseven** [comment]
That was the error, gave me new one. Also no option still 
![2](https://user-images.githubusercontent.com/54422205/219105278-5d7cfe13-2d5f-4cba-8074-baafde5dc907.PNG)
I'll try reinstalling the extension

**Comment by trihardseven** [comment]
Yeah reinstalling it fixed it. I was using an older version even though check updates said it was latest.
