### ISSUE TITLE
[Feature Request] Ability to move images to directories defined in the saved directories

### ISSUE THREAD

**Issue by neo-js** [AlUlkesh/stable-diffusion-webui-images-browser#39]
It quickly becomes necessary to manage all the images produced and not all users have direct folder access to the system running the webui.

The ability to move images to custom directories would be very useful for webui only users.  We have a tendency to use our phones to access the webui and run ideas when we are not at our PCs.

The mockup by @Woisek mentioned in #5 would be a good design, though I would suggest a dropdown of directories that comes from the saved directories defined on the Others tab.

![Mockup](https://user-images.githubusercontent.com/122026301/218328464-42d0c2bd-f235-47ca-999e-eccab020930f.png)

Thank you for your great work on this extension!  It has made webui only access possible for my team.

**Comment by AlUlkesh** [comment]
@Woisek, @neo-js
Here's the copy/move function. It follows the same rules as other copies/moves according to this setting:
![image](https://user-images.githubusercontent.com/99896447/219941620-5a9c1b62-1644-4dc6-8473-9b2ef0c4d834.png)

Let me know, if this does what you had in mind.

**Comment by Woisek** [comment]
@AlUlkesh 
OK, tested it out and it looks good so far. Just a minor thing to correct and a simple to say, but probably not so easy request to do:
When a new path is saved in "Others", it is not available in the other tabs till Gradio is restarted. Should be instantely reflected after creation/edit/deletion of paths.

Now the a bit complicated thing:
The moving of one picture is perfect. Well ... _one_ picture. What I'm now missing (actually some time before), is a batch function. Not only for copy/moving, but also for deleteing.
I know for the latter you have the "delete the next x", but that's not the same thing and counting the small images is .. well ... :). We need some options when we at the overview of the gallery.

So my suggestion would be to add check boxes in the right upper corner on the previews when in overview and ideally also when single viewed. Those checked images could then be manipulated in dfferent ways like copy/move/delete with their appropiate buttons. A "check all" button to check/uncheck all images on the current page would also be helpful to quickly do some actions, especially for those who have their image display settings per page at a higher number.

Again, thank you for this great work. It's getting better and better. :)

**Comment by AlUlkesh** [comment]
This commit should do the auto-refresh on the dropdown.

The other thing, I'm afraid, won't be possible because... wanna guess?

Yeah, because of gradio. That whole thumbnail view is handled by gradio. Even with tricks, I don't think you can put checkboxes in the middle of that. And even if, I'm sure it would break everything.

**Comment by Woisek** [comment]
Gradio ... the bane of all good development ... :D
Damn, sometimes I think a good developed standard website could all this handle 1000x better ... :/
Moving 20+ images only one by one to another folder ... that's a big drawback and not userfriendly at all ...

Thanks for looking into it. But maybe we get lucky and you find something, or Gradio gets mature ... who knows. :)

**Comment by AlUlkesh** [comment]
Yeah, I agree, I think a web app framework and a simple server would work better for us. Oh well, maybe there'll be a webui 2.0...

**Comment by neo-js** [comment]
Thank you, it's working very well.

I'll be looking more into the Gradio Gallery and see what I can figure out.  Thanks again for looking into that.
