### ISSUE TITLE
Support Dynamic Prompts templates (Would Be Nice)

### ISSUE THREAD

**Issue by axemaster** [AlUlkesh/stable-diffusion-webui-images-browser#41]
When an image has a template and a prompt, and the user presses a button to send the info to txt2img, the user could have the option to send the template instead of the actual prompt. Right now it's a manual copy paste, so there is a very workable work-around. This is a "would be nice" feature request.

**Comment by axemaster** [comment]
I don't know if this functionality would go into the browser or the main somehow UI actually. I'm dropping this here for now.

**Comment by AlUlkesh** [comment]
Actually... that would have to be an issue for the Dynamic Prompts extension.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7339#issuecomment-1432590258
