### ISSUE TITLE
Support of other extensions

### ISSUE THREAD

**Issue by younyokel** [AlUlkesh/stable-diffusion-webui-images-browser#43]
Will there be a support of buttons "Send to" for other extensions such as OpenOutpaint and InstructPix2pix?

**Comment by AlUlkesh** [comment]
I can look into OpenOutpaint.

However for InstructPix2Pix I think that's no longer necessary, since it's been integrated into webui. You can just use sendto img2img.

**Comment by younyokel** [comment]
Thanks. I didn't know about instruct pix2pix though!

**Comment by AlUlkesh** [comment]
@younyokel 
Send to OpenOutpaint works now.
