### ISSUE TITLE
Feature Request: Store Ranking in image metadata

### ISSUE THREAD

**Issue by ouoertheo** [AlUlkesh/stable-diffusion-webui-images-browser#45]
Howdy, I love your extension, it has really great features 😄 

I've been using the ranking feature a lot, and noticed when I moved my images, the rankings were lost. I'm assuming that data is getting stored in the sqlite db with the extension. 

Is it possible to add those into the image metadata for image portability and to be used by other tools?

**Comment by AlUlkesh** [comment]
Yes, good points. Thanks.

I'll put in an option to save in the exif and then some more maintenance options like:
- Change path in database
- Read ranking from exif

**Comment by AlUlkesh** [comment]
I haven't gotten around to the "storing in exif" thing yet, but the latest commit contains a feature, that should help with this:

- If a ranking is not found with the full pathname, another try is made with the filename (https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/discussions/57)

**Comment by AlUlkesh** [comment]
This is in now. Must be activated in settings:
![image](https://user-images.githubusercontent.com/99896447/222921897-ad8a25ff-f5d1-4269-8a9a-8279e43758b0.png)

I decided against turning it on by default, since it changes the image strictly speaking. The user should have control over that.

**Comment by ouoertheo** [comment]
Thanks for taking this on :D
Is it possible that this caused the below exception?
```
Image Browser: Upgrading database from version 1 to version 3
Error executing callback ui_tabs_callback for E:\AI\Automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py
Traceback (most recent call last):
  File "E:\AI\Automatic1111\stable-diffusion-webui\modules\script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "E:\AI\Automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 1030, in on_ui_tabs
    create_tab(tab, current_gr_tab)
  File "E:\AI\Automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 725, in create_tab
    db_version = wib_db.check()
  File "E:\AI\Automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\wib\wib_db.py", line 339, in check
    migrate_path_recorder_dirs(cursor)
  File "E:\AI\Automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\wib\wib_db.py", line 246, in migrate_path_recorder_dirs
    cursor.execute('''
sqlite3.IntegrityError: UNIQUE constraint failed: path_recorder.path
```
I could probably just re-download the plugin, but if I can keep my rankings, that would be awesome

**Comment by AlUlkesh** [comment]
No, I don't think that's related.

The script is trying to upgrade your database, but apparently it finds some unexpected double entries.

Let's start by checking what is actually in your database. Can you run this from the extension base directory:
https://github.com/AlUlkesh/debug-helper/blob/main/path_recorder_list.py

It will print out blocks of 4 lines. Is the 4th line the same somewhere?

**Comment by ouoertheo** [comment]
Yep, here's the output
```
outputs\landscapes
0
outputs\landscapes [0]
E:\AI\Automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\outputs\landscapes

outputs\characters
0
outputs\characters [0]
E:\AI\Automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\outputs\characters

outputs\project
0
outputs\project [0]
E:\AI\Automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\outputs\project

E:\AI\Automatic1111\stable-diffusion-webui\outputs
0
E:\AI\Automatic1111\stable-diffusion-webui\outputs [0]
E:\AI\Automatic1111\stable-diffusion-webui\outputs

E:\AI\Automatic1111\stable-diffusion-webui\outputs\characters
0
E:\AI\Automatic1111\stable-diffusion-webui\outputs\characters [0]
E:\AI\Automatic1111\stable-diffusion-webui\outputs\characters
```

**Comment by AlUlkesh** [comment]
That's the complete output? Or are these the doubles you found?

**Comment by ouoertheo** [comment]
That's the complete output

**Comment by ouoertheo** [comment]
If you wanted to work more in realtime, I'm on Discord `ouoertheo#7264`. I know this probably isn't a relevant thread for working this problem

**Comment by AlUlkesh** [comment]
Found it. Let's continue here: #63
