### ISSUE TITLE
`None` ranking filter only shows images where `none` ranking has been assigned explicitly

### ISSUE THREAD

**Issue by ouoertheo** [AlUlkesh/stable-diffusion-webui-images-browser#46]
Not sure if this is a bug or intended, but when I filter by `none` ranking, I only get images where I explicitly selected `none` ranking. I would expect it to also include images that have never been ranked.

**Comment by AlUlkesh** [comment]
I don't know what was intended.

But I think I'll change this as follows:
- None filter shows everything without a rank
- Setting an image to none removes a rank, if it has one (as opposed to setting the rank to the value "None")

**Comment by Klace** [comment]
> I don't know what was intended.
> 
> But I think I'll change this as follows:
> 
> * None filter shows everything without a rank
> * Setting an image to none removes a rank, if it has one (as opposed to setting the rank to the value "None")

Not intended, None should have never been saved in the first place :) My bad.

Must still include explicitly assigned "None" in the filter results for any files created before this fix.

**Comment by AlUlkesh** [comment]
@Klace
Thanks for the clarification. :smile:

**Comment by AlUlkesh** [comment]
The latest commit should fix this (#57)
