### ISSUE TITLE
Feature Request: Carry over ranks

### ISSUE THREAD

**Issue by Kapowpenguin1** [AlUlkesh/stable-diffusion-webui-images-browser#53]
I've noticed that the ranking of an image in "text2img" seems to be cleared if moved via "Move to favorites". Is it possible to retain the ranking?

**Comment by AlUlkesh** [comment]
That's because the info is saved with the pathname as a key. Would make sense to change it, when the file is moved. I'll look into it.

**Comment by AlUlkesh** [comment]
The latest commit contains a feature, that should help with this:
- If a ranking is not found with the full pathname, another try is made with the filename (#57)

**Comment by Kapowpenguin1** [comment]
unfortunately, nothing seems to have changed. on version 4cbcd1de and "Move to favorites" still does not retain the image's ranking. is there a setting/parameter i should be checking/changing?

**Comment by Kapowpenguin1** [comment]
i put "ranking_list" under "stable-diffusion-webui-images-browser", opened the directory in terminal, did "python ranking_list.py" and got "sqlite3.OperationalError: no such column: name"

**Comment by AlUlkesh** [comment]
That suggests that your database didn't get upgraded to version 2, like should have happened, when you first ran the extension with the new commit.

Did you restart webui after updating?

**Comment by Kapowpenguin1** [comment]
i restarted through the webui interface, but ig that wasn't enough? i closed the console and reran the user batch and the ranking script started working properly. the ranks are also transferred properly now. thanks for your help!

**Comment by AlUlkesh** [comment]
Ah, good. Yes, that has happened before. Something's not right with updating from the web interface.
