### ISSUE TITLE
[Bug Report] Preview Tiling does not work

### ISSUE THREAD

**Issue by BoosterCore** [AlUlkesh/stable-diffusion-webui-images-browser#55]
Preview Tiling do not work, It just display a blank black.

**Comment by AlUlkesh** [comment]
Can you update the extension to the latest version and set the debugging option? (Settings - Image Browser - Print debug logs to the console)

Then restart webui and run to the error again and post the console log.

And also check if there is something in the browser javascript console log (https://wordpress.org/documentation/article/using-your-browser-to-diagnose-javascript-errors/#step-3-diagnosis).

**Comment by BoosterCore** [comment]
> Can you update the extension to the latest version and set the debugging option? (Settings - Image Browser - Print debug logs to the console)
> 
> Then restart webui and run to the error again and post the console log.
> 
> And also check if there is something in the browser javascript console log (https://wordpress.org/documentation/article/using-your-browser-to-diagnose-javascript-errors/#step-3-diagnosis).

thanks，it is working now！
