### ISSUE TITLE
Feature request: minimum aesthetic_score filter in Image Browser accepts a range

### ISSUE THREAD

**Issue by axemaster** [AlUlkesh/stable-diffusion-webui-images-browser#56]
I opened this issue in the aesthetic_score extension repo and he said it belongs here.

I'd like to enter an open range like "-5" (up to five i.e. 5 or less),
or a closed range like "3.0-4.5" (3 to 4.5 inclusive)

**Comment by AlUlkesh** [comment]
Or a `maximum aesthetic_score` in addition to the current `minimum aesthetic_score`?

**Comment by AlUlkesh** [comment]
This is in now:

![image](https://user-images.githubusercontent.com/99896447/222926173-f068c4c7-a42c-41f6-9634-ccc4c4cd3be0.png)
