### ISSUE TITLE
Images left in appdata\local\temp

### ISSUE THREAD

**Issue by Venicus** [AlUlkesh/stable-diffusion-webui-images-browser#60]
An issue with the previous repository version of this extension (https://github.com/yfszzx/stable-diffusion-webui-images-browser/issues/56) appears to still be active. Whenever images are loaded, they are seemingly unnecessarily cached as duplicates in **AppData\Local\Temp**. To reproduce, just view any folder in the image browser. If this is strictly required, it might be good if the temp directory used could be defined by the user, and/or if there were an option to clear these temp files on exit. There were multiple gigabytes of images in there I had no idea existed, and it seems like that shouldn't be necessary considering the saved images already exist in other directories, although I assume it was set up this way for a reason.

**Comment by AlUlkesh** [comment]
The extension doesn't use a temp directory in its code. If those files are there, they're put there by gradio.

I would have expected that to be handled globally by webui in its ui_tempdir.py. How did you set these options?

![image](https://user-images.githubusercontent.com/99896447/222666799-49507cb3-0873-4d98-8d2e-4c3f9eb9cca3.png)

**Comment by Venicus** [comment]
> The extension doesn't use a temp directory in its code. If those files are there, they're put there by gradio.
> 
> I would have expected that to be handled globally by webui in its ui_tempdir.py. How did you set these options?
> 
> ![image](https://user-images.githubusercontent.com/99896447/222666799-49507cb3-0873-4d98-8d2e-4c3f9eb9cca3.png)

Thanks for the follow-up! I suspect you're right regarding Gradio. I've set a different temp directory in the settings in your screenshot, which doesn't appear to have any effect on this issue. Images generated in txt2img or img2img still appear in their normal output folders. The "Cleanup non-default temporary directory when starting webui" option doesn't appear to affect this behavior one way or another either. It's possible the problem is with the webUI itself not honoring the temp file selection maybe, as I did just notice a few images from the controlnet extension end up in this appdata folder too, so this might not be specific to the image browser so much as just more easily noticed with it.

**Comment by AlUlkesh** [comment]
I can look into it, if you can find a way to reproduce this. I've tried a couple of things just now, but no temp files are written.

**Comment by maxiy01** [comment]
From my experience these files are generated by gradio if --share option is used.

**Comment by AlUlkesh** [comment]
Let me know if things work according to those webui settings now.

**Comment by Venicus** [comment]
> Let me know if things work according to those webui settings now.

Splendid! Yep, it now appears to respect the temp folder specified in the webUI settings! Nicely done! I greatly appreciate your attention to that as well as your suggestions and consideration. I'm a little perplexed that it needs to generate these, but as you previously said that's presumably on Gradio, not the extension.

**Comment by AlUlkesh** [comment]
Thanks. Good to hear it's working.

**Comment by Woisek** [comment]
I'm afraid to say, that here it doesn't work. It still says:

Traceback (most recent call last):
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 956, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 3742, in postprocess
    file_path = self.make_temp_copy_if_needed(img)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 376, in make_temp_copy_if_needed
    f = tempfile.NamedTemporaryFile()
  File "F:\Programme\Python310\lib\tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "F:\Programme\Python310\lib\tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "F:\Programme\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'T:\\systemp\\sd_temp_files\\tmp9stftz59'

T:\systemp\sd_temp_files is the dir I entered in the settings. The "sd_temp_files" is the folder that should be created if not existent. Any suggestions? :(

**Comment by AlUlkesh** [comment]
@Woisek 
What was the action the preceeds this error? Changing the temp setting?

Also can you post a screenshot of the temp settings?

**Comment by Woisek** [comment]
@AlUlkesh 
>What was the action the preceeds this error? Changing the temp setting?

No, it was after clicking on "refresh" (right side of the index display), because "error" is shown everywhere when this directory doesn't exist.

![temp](https://user-images.githubusercontent.com/122026301/222921786-374e56c3-1cec-4cf9-afb9-49f067fb8d97.png)
![error](https://user-images.githubusercontent.com/122026301/222921856-b46e29ee-e02e-4b34-9f0e-a45e7cbe7b69.png)

**Comment by AlUlkesh** [comment]
And you restarted webui and the browser window after the update?

**Comment by Woisek** [comment]
Several times, because the GUI has always to be restarted a second time after an update.

**Comment by chuckkay** [comment]
this is still an issue for me..

every time I view images in on image browser tab, it creates duplicate images in whatever folder is set up as the temp folder, after restarting webui or restarting automatic 1111 the temp png files are still there left behind.

i am running a clean install with you latest update, i can confirm it is only depositing the files in the temp folder when you hit next page or previous page and it is showing an image for the first time....

**Comment by AlUlkesh** [comment]
Did you set this up in webui settings?

![image](https://user-images.githubusercontent.com/99896447/227069524-e784394b-9107-4ae5-a8f7-8be02c53657c.png)

**Comment by chuckkay** [comment]
yes i did, but at first it was blank and all the pngs were going to C:\Users\......\AppData\Local\Temp  and wouldn't get deleted on web-ui restart, then i changed that setting to C:\AI\output\temp.. now they all show up there but still never delete...basically giving me 2 of every png file....

**Comment by chuckkay** [comment]
also i did a clean install

**Comment by AlUlkesh** [comment]
Just to clarify, you ticked the Cleanup checkbox, but they still don't get deleted on the next webui start?
