### ISSUE TITLE
Feature request: open image in browser directory

### ISSUE THREAD

**Issue by LiJT** [AlUlkesh/stable-diffusion-webui-images-browser#62]
![1](https://user-images.githubusercontent.com/11270197/222941604-2767cc8c-6937-41f7-86a5-0380ec16e4d3.png)

Currently there is no button for me to open the image in directory, i wish there is a button down below like this one
![3](https://user-images.githubusercontent.com/11270197/222941637-c77c9ab4-0adb-477c-897e-b41ce3f47910.png)

So i can open the browser and find where this image is

**Comment by AlUlkesh** [comment]
@LiJT Should work now.

**Comment by LiJT** [comment]
> @LiJT Should work now.

WOW thats fast! Thank you man!
