### ISSUE TITLE
Send to ControlNet

### ISSUE THREAD

**Issue by MrKuenning** [AlUlkesh/stable-diffusion-webui-images-browser#67]
Can we have an option to send to ControlNet?

It could be a useful way to browse openpose images and send them to ControlNet.

**Comment by AlUlkesh** [comment]
@MrKuenning 
How exactly would you expect this to work?

You can have multiple ControlNets in txt2img and again in img2img. How should be determined where to send the image?

**Comment by MrKuenning** [comment]
One way would be like how the open pose editor extension does it.

![Screenshot_20230311-025826.png](https://user-images.githubusercontent.com/16549268/224483035-89c4af5a-3fb0-4733-84c9-2aa1fd139ab1.png)

There is a button for controlnet in t2i and i2i and a drop down to select which controlnet layer.

**Comment by AlUlkesh** [comment]
Here it is. Let me know, if it works, as you expect.

**Comment by MrKuenning** [comment]
That works great.  Thanks!

**Comment by EllangoK** [comment]
Yeah this for sure a great feature thanks AlUlkesh, I've also been using control net a lot recently so this really helpful.

@MrKuenning just to lyk in case you don't, but you can add your own folders as a separate tab next to txt2img, img2img and the rest on the bar up there in settings. So it might be a bit better instead of accessing it from others.

**Comment by MrKuenning** [comment]
Funny you mention that, I just found that setting and was coming back to say so.

![2023-03-11 11_59_23-NVIDIA GeForce Overlay DT](https://user-images.githubusercontent.com/16549268/224511401-308019a8-092a-4a0c-9c5f-4ff321a70bf2.jpg)

**Comment by MrKuenning** [comment]
I do have one question.  My buttons have an odd blank space and button wrap.

![2023-03-11 12_01_47-NVIDIA GeForce Overlay DT](https://user-images.githubusercontent.com/16549268/224511484-9ecf6f9e-c276-4eaa-ace9-44a55742314a.jpg)

It doesn't break functionality, just wanted to point it out as your image shows them all on one line.

**Comment by EllangoK** [comment]
Yeah its the same for me, it is because of these lines
https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/blob/7dbd508461af2b533d931ee3f03118b13b9f05d5/scripts/image_browser.py#L952-L953
deleting it fixes that but @AlUlkesh you also might want it at the end so idk

### At the end

![image](https://user-images.githubusercontent.com/23466035/224513130-9c77484c-8f86-44e6-a93b-3ce97954ba5b.png)

### No breaks

![image](https://user-images.githubusercontent.com/23466035/224513139-f0dc8031-1434-40f5-a3b0-dedfe5dc2bfc.png)

There is a difference but imo I think no breaks is better and probably scales properly when resized for other people.

**Comment by AlUlkesh** [comment]
Always good to hear something you develop is actually used. Thanks.

Those spaces are there to keep the ControlNet elements together. But apparently only with my window size.

That whole column right of the image gallery has been extremely finicky. It doesn't group like I'd expect it to do from what I read on the gradio site. So it's mostly trial and error, to make the grouping make somewhat sense.

**Comment by EllangoK** [comment]
Yeah you are right, I was thinking initiallly shouldn't it just easy to put it into two rows?

But yeah no, 

```
                        with gr.Row():
                            if tab.name != favorite_tab_name:
                                favorites_btn = gr.Button(f'{copy_move[opts.image_browser_copy_image]} to favorites', elem_id=f"{tab.base_tag}_image_browser_favorites_btn")
                            try:
                                send_to_buttons = modules.generation_parameters_copypaste.create_buttons(["txt2img", "img2img", "inpaint", "extras"])
                            except:
                                pass
                            sendto_openoutpaint = gr.Button("Send to openOutpaint", elem_id=f"{tab.base_tag}_image_browser_openoutpaint_btn", visible=openoutpaint)
                        with gr.Row():
                            sendto_controlnet_txt2img = gr.Button("Send to txt2img ControlNet", visible=controlnet)
                            sendto_controlnet_img2img = gr.Button("Send to img2img ControlNet", visible=controlnet)
                            controlnet_max = opts.data.get("control_net_max_models_num", 1)
                            sendto_controlnet_num = gr.Dropdown(list(range(controlnet_max)), label="ControlNet number", value="0", interactive=True, visible=(controlnet and controlnet_max > 1))
```
for some reason gives this
![image](https://user-images.githubusercontent.com/23466035/224516018-14c40a51-2140-460b-9970-bd9c77fbc446.png)
two columns still gives two columns.

But yeah very weird, did not realise.

**Comment by EllangoK** [comment]
Alright this should work

```
with gr.Column():
    with gr.Row():
        if tab.name != favorite_tab_name:
            favorites_btn = gr.Button(f'{copy_move[opts.image_browser_copy_image]} to favorites', elem_id=f"{tab.base_tag}_image_browser_favorites_btn")
        try:
            send_to_buttons = modules.generation_parameters_copypaste.create_buttons(["txt2img", "img2img", "inpaint", "extras"])
        except:
            pass
        sendto_openoutpaint = gr.Button("Send to openOutpaint", elem_id=f"{tab.base_tag}_image_browser_openoutpaint_btn", visible=openoutpaint)
    with gr.Row():
        sendto_controlnet_txt2img = gr.Button("Send to txt2img ControlNet", visible=controlnet)
        sendto_controlnet_img2img = gr.Button("Send to img2img ControlNet", visible=controlnet)
        controlnet_max = opts.data.get("control_net_max_models_num", 1)
        sendto_controlnet_num = gr.Dropdown(list(range(controlnet_max)), label="ControlNet number", value="0", interactive=True, visible=(controlnet and controlnet_max > 1))
```

![image](https://user-images.githubusercontent.com/23466035/224516451-20a6d078-aac5-429e-9626-0916ab505a8b.png)

I'll drop a PR
