### ISSUE TITLE
Feature Request: Disable parts of side bar 

### ISSUE THREAD

**Issue by EllangoK** [AlUlkesh/stable-diffusion-webui-images-browser#68]
I never use the aesthetic score stuff or the copy to directory so just an option for user to disable. Probably either a multiselect or dropdown so users don't need to like worry about the names. 

In case you are worried we should be able to avoid any issues when we add new stuff unlike with the custom tab options, since this is only a disable list. Thus if a new item is added to the sidebar by default it will show up for all users as a new item can't be in the disable list.

**Comment by missionfloyd** [comment]
[Here's the sidebar](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/blob/main/scripts/image_browser.py#L861-L908). Add `, visible=False` to anything you want to hide. You can even hide the entire thing by adding it to `gr.Column()` on line 861.

If these things had `elem_id` set, we could do this with CSS.

**Comment by EllangoK** [comment]
Thanks but I already know how to do it, I've modified this code a bunch already. I'm the one who added keybindings and custom tab options.

Also we should not do it with css, we can just add a multiselect in settings and keep it in the python code, so its simpler.
