### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by chuckkay** [AlUlkesh/stable-diffusion-webui-images-browser#72]
i get this error message several times in termanal window on start up, but only with stable-diffusion-webui-images-browser extention installed.

C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Slider, please remove them: {'precision': 0}

![image](https://user-images.githubusercontent.com/10617746/223627831-e3264fec-6534-455b-aa94-ee3e526abe06.png)

**Comment by AlUlkesh** [comment]
Those are warnings. How did you set these options:

Settings - Image Browser:
- Print warning logs to the console
- Print debug logs to the console

**Comment by chuckkay** [comment]
unchecked
![image](https://user-images.githubusercontent.com/10617746/223816368-282a5990-d373-467b-bf1e-2a35289a4541.png)

**Comment by AlUlkesh** [comment]
Can you check the debug option, restart webui and then post the complete console log?

**Comment by AlUlkesh** [comment]
@chuckkay 
Anything new here?

**Comment by chuckkay** [comment]
C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'equal_height': True}
  warnings.warn(
C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Slider, please remove them: {'precision': 0}
  warnings.warn(
C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Tab, please remove them: {'elme_id': 'TabSave'}
  warnings.warn(
C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'scale': 0.5}
  warnings.warn(
C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py:805: UserWarning: Expected 17 arguments for function <function get_image_page at 0x000002859C74AF80>, received 16.
  warnings.warn(
C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py:809: UserWarning: Expected at least 17 arguments for function <function get_image_page at 0x000002859C74AF80>, received 16.
  warnings.warn(
C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Number, please remove them: {'min': 1}
  warnings.warn(
C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Dropdown, please remove them: {'scale': 0.3}
  warnings.warn(
C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Slider, please remove them: {'min': 0, 'max': 100}
  warnings.warn(
C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Slider, please remove them: {'min': 1, 'max': 50}
  warnings.warn(
C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Number, please remove them: {'live': True}
  warnings.warn(
C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Button, please remove them: {'full_width': True}
  warnings.warn(

**Comment by chuckkay** [comment]
should i run --ui-debug-mode or gradio debug mode ?
still getting 
C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'equal_height': True}
  warnings.warn(
C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Slider, please remove them: {'precision': 0}
  warnings.warn(
C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Tab, please remove them: {'elme_id': 'TabSave'}
  warnings.warn(
C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'scale': 0.5}

**Comment by AlUlkesh** [comment]
If you suspect the extension let's start there:
Settings - Image Browser - Print warning logs to the console
Restart webui and then post the complete console log.

**Comment by aibaby1991** [comment]
kwarg parameters in Row, please remove them: {'scale': 0.5}
the error 
should be edit the image_broeser.py
line 1118
change to
                    with gr.Row({'scale': 0.5) as sort_panel:
->                    with gr.Row() as sort_panel:

Thank you
K Lam

**Comment by AlUlkesh** [comment]
Thanks, @aibaby1991 !
