### ISSUE TITLE
Sending to txt2img/img2img tab while using an UmiAI wildcard (for example) still causes errors (red labels everywhere in mentioned tabs).

### ISSUE THREAD

**Issue by mart-hill** [AlUlkesh/stable-diffusion-webui-images-browser#83]
It's like I mentioned in the title, and I already reposted it back in the time for the WebUI, but it's probably **dynamic prompts** extension's fault?

When I "paste" an image with "clean" info (without a `Wildcard prompt: "blablabla"` part in the file info), the error disappears and I'm able to continue. 🙂 
Otherwise, I'll get this:
```
Traceback (most recent call last):
  File "O:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "O:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "O:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "O:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "O:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "O:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "O:\AI\stable-diffusion-webui\modules\generation_parameters_copypaste.py", line 340, in paste_func
    params = parse_generation_parameters(prompt)
  File "O:\AI\stable-diffusion-webui\modules\generation_parameters_copypaste.py", line 264, in parse_generation_parameters
    v = v[1:-1] if v[0] == '"' and v[-1] == '"' else v
IndexError: string index out of range
```
This error is also happening while using PNG Info tab, so, in the end, it's a wider issue, but maybe at least in this extension, it could be "workaround'ed"? 😅 

Would it be possible for the Images Browser to insert the "wildcard" part of the text to the positive prompt, if/when the extension encounters it? I think, that, at least in UmiAI's case, that extension doesn't react to its "tags", when inserted into the negative prompt area. I used the "classroom" tag from UmiAI with such `<[classroom]>` syntax. That causes the Umi to make a random choosing of the parts, which are included as a description of this tag in Umi's .yaml file.

Example generation, which causes error on "import" to txt2img:

![img](https://user-images.githubusercontent.com/55754730/224430895-5c84c01c-248b-4f59-91f0-d17bb997bed1.png)

**Comment by f0lie** [comment]
For clarity, the pnginfo looks like this:

<img width="988" alt="image" src="https://user-images.githubusercontent.com/9092074/224462335-6716ef10-63e7-487f-bd12-aee6d1e50a9b.png">

I was able to reproduce this problem on my machine as well.

**Comment by f0lie** [comment]
After running the debugger the root of the problem is that, "File Includes" is empty.

<img width="181" alt="Screenshot 2023-03-10 195829" src="https://user-images.githubusercontent.com/9092074/224463826-a1650cf9-ede3-4167-bfd0-883e274abc03.png">

The line I linked tries to read from this empty string and throws an error. I am not sure what "File Includes" means in the context of the extension that creates this.

There are two ways to solve this problem:

1. Update automatic1111 main repo to handle empty strings correctly.
2. Update the extension that is adding "File Includes" to not include empty lines.

I think (1) is better but the main repo is not accepting PRs for some reason.

**Comment by mart-hill** [comment]
Thank you for the insight, @f0lie!

**Comment by f0lie** [comment]
@mart-hill If you want to patch it on your local repo, just change the line to:

```python
if v:
  v = v[1:-1] if v[0] == '"' and v[-1] == '"' else v
```

It shouldn't change the behave of anything else. It seems like that code is trying to remove quotes from parsed inputs. I guess they did that because the regex was already getting long.

**Comment by mart-hill** [comment]
Thank you so much! I'll try this instant! 🙂

**Comment by mart-hill** [comment]
I'll mention, that main AUTO1111 repo finally patched it, I believe. I no longer needed to edit **generation_parameters_copypaste.py** file after today's `git pull`.🙂

**Comment by f0lie** [comment]
It seems like they fixed the regex itself as opposed to the hotfix I suggested. It's better to fix root cause problems than patchy hacks.

**Comment by mart-hill** [comment]
Oh. though, I noticed that the `if v:` stayed in that file on my side, since I didn't have to remove it, when I used `git pull` a hour and a half ago. Curious, because the repo has this .py file without your "patchy hack" 🙂 
I'll use `git pull` again and test!

**Comment by mart-hill** [comment]
I checked and the **generation_parameters_copypaste.py** file from the main repo doesn't have this issue fixed for now, so I'll edit the .py file to add `if v:`.🙂
