### ISSUE TITLE
AttributeError: module 'scripts.wib.wib_db' has no attribute 'fill_work_files'

### ISSUE THREAD

**Issue by f0lie** [AlUlkesh/stable-diffusion-webui-images-browser#85]
```
Traceback (most recent call last):
  File "C:\Users\f0lie\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\f0lie\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\Users\f0lie\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\f0lie\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\f0lie\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\f0lie\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\f0lie\ai\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 729, in get_image_page
    filenames = get_all_images(img_path, sort_by, sort_order, keyword, tab_base_tag_box, img_path_depth, ranking_filter, aes_filter_min, aes_filter_max, exif_keyword, negative_prompt_search, use_regex, case_sensitive)
  File "C:\Users\f0lie\ai\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 644, in get_all_images
    wib_db.fill_work_files(cursor, fileinfos)
AttributeError: module 'scripts.wib.wib_db' has no attribute 'fill_work_files'
```

It appears that the offending line is this:

https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/blob/fe445ddf26d3b311f563e0763c7f3041fc5391cf/scripts/image_browser.py#L644

Which is trying to reference this:

https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/blame/fe445ddf26d3b311f563e0763c7f3041fc5391cf/scripts/wib/wib_db.py#L727

It looks like that file was touched in the most recent commit:

https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/commit/fe445ddf26d3b311f563e0763c7f3041fc5391cf#diff-ecf545477a05f9b41eff68f1aadd63b431d17a13baa23a6b25375246d9b4ffc6R727

I am not quite sure what is going on here. I opened up vscode and I can verify that `fill_work_files` exists in the right place. Also, this doesn't look like a typo problem since `fill_work_files` is spelled correctly.

I am running on Windows so maybe that impacts what modules are being imported.

**Comment by f0lie** [comment]
I reloaded the browser and for some reason, it worked.

I really don't know what is going on here. But I guess it's fixed? If I run into this again, I'll just open the issue.

**Comment by Gazzoo-byte** [comment]
Just updated to the latest webui version and image browser version and I'm getting this exact error, survives a UI reload on my machine

**Comment by AlUlkesh** [comment]
How exactly are you restarting? Hitting "Reload UI" won't be enough. That will only restart gradio.

Webui needs to be restarted. Also start with a fresh web page.

**Comment by Gazzoo-byte** [comment]
> How exactly are you restarting? Hitting "Reload UI" won't be enough. That will only restart gradio.
> 
> Webui needs to be restarted. Also start with a fresh web page.

In my instance I was initially just using the reload UI button, however when this didn't resolve the issue I tried fully closing the webui by doing ctrl+c in the cmd prompt it was run from to no success

**Comment by AlUlkesh** [comment]
Ok, thanks, I'll try to reproduce it.

**Comment by nicknack23** [comment]
I had the exact same problem. The image browser broke completely after the update (no images displayed, just "error"), but  deleting wib.sqlite3 fixed it. I think something needs to be done - Auto1111 has lots of newbies who might not know you can look up issues in the Github repo. Maybe catch the error and write a suggestion to delete the sqlite db in the console?

**Comment by f0lie** [comment]
I reopened this issue because there is clearly multiple people running into this. I personally haven't ran into this problem again but it seems like we need to do some root analysis here.

**Comment by AlUlkesh** [comment]
@nicknack23 @f0lie
How exactly did you update? From the extensions tab with restart UI?

**Comment by f0lie** [comment]
> @nicknack23 @f0lie
> How exactly did you update? From the extensions tab with restart UI?

Yea, I do it with the extensions tab and restart the UI.

**Comment by AlUlkesh** [comment]
I think I found the issue. While webui's "Reload UI" does reload the extension's main module, it does not do so for any sub-modules. So essentially half the code ran in the new and half of it in the old version. Which of course caused mayhem.

I am now force reloading submodules at the start of the main module. I believe that should fix it.
