### ISSUE TITLE
Prevent actions before gradio is loaded

### ISSUE THREAD

**Issue by AlUlkesh** [AlUlkesh/stable-diffusion-webui-images-browser#91]
While debugging my latest fix for the delete issue, I noticed that the current code sometimes does actions on gradio elements, before gradio is fully loaded.

I already have a solution, that I am also implementing for the delete issue. This needs to be applied to the other code too.

**Comment by AlUlkesh** [comment]
See #94

**Comment by missionfloyd** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/a9fed7c364061ae6efb37f797b6b522cb3cf7aa2/script.js#L24-L26

https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/a9fed7c364061ae6efb37f797b6b522cb3cf7aa2/javascript/extraNetworks.js#L47

**Comment by AlUlkesh** [comment]
Oh, that's cool. I didn't know these existed. I'll try to use them instead. Thanks.
