### ISSUE TITLE
Image refresh problem when switching pages

### ISSUE THREAD

**Issue by JarringBye** [AlUlkesh/stable-diffusion-webui-images-browser#92]
When I click on the next page, the images in the grid always change one by one, and when there are too many images I can't notice which ones have changed and which ones haven't refreshed. Therefore, I suggest a new function: display a loading logo when the image is not refreshed

**Comment by AlUlkesh** [comment]
I'm not really sure what you mean with "change one by one". Here is how it looks for me:

https://user-images.githubusercontent.com/99896447/226165935-a1c59853-4076-4da7-80f7-b3b2e5852756.mp4

**Comment by AlUlkesh** [comment]
Thanks for the video. I'll see if I can replicate it somehow. Perhaps put some sleeps in the code.

**Comment by Aamir3d** [comment]
> When I click on the next page, the images in the grid always change one by one, and when there are too many images I can't notice which ones have changed and which ones haven't refreshed. Therefore, I suggest a new function: display a loading logo when the image is not refreshed

What are your system specs?
Slow loading could be a side effect of low RAM or a slow hard disk.

**Comment by JarringBye** [comment]
> > 当我点击下一页时，网格中的图像总是一张一张地变化，当图像太多时我无法注意到哪些已经改变了哪些没有刷新。因此，我建议一个新的功能：在图片不刷新时显示一个loading logo
> 
> 您的系统规格是什么？ 加载缓慢可能是内存不足或硬盘速度慢的副作用。

I deployed the project on the server, possibly because the images are too large and the bandwidth is insufficient when loading multiple images at once

**Comment by AlUlkesh** [comment]
@JarringBye 
There is an option now to load thumbnails at smaller sizes. Perhaps that can help in your case?

![image](https://user-images.githubusercontent.com/99896447/229996679-1e8fa19e-993e-48b9-b6ad-7fb81730c4e8.png)

**Comment by JarringBye** [comment]
> @JarringBye 现在有一个选项可以加载较小尺寸的缩略图。也许这对您的情况有帮助？
> 
> ![图像](https://user-images.githubusercontent.com/99896447/229996679-1e8fa19e-993e-48b9-b6ad-7fb81730c4e8.png)

thank you! I will try
