### ISSUE TITLE
58c374c, the "maintenance tab" enabled but i had it disabled, when i enable it, now I got two "maintenance tabs"

### ISSUE THREAD

**Issue by bryanray** [AlUlkesh/stable-diffusion-webui-images-browser#93]
58c374c, the "maintenance tab" enabled but i had it disabled, when i enable it, now I got two "maintenance tabs"

**Comment by bryanray** [comment]
SOLVED:
list of active tabs....
OMG< literally this is where the double comes from, i delete the "maintenance" from the list and it is gone now, but why tho, 2 options, a list and a checkbox :)))
it is confusing....

**Comment by AlUlkesh** [comment]
I put it in, just to confuse you :sunglasses:

No, seriously, the list and the maintenance were developed in parallel. I'll eventually combine them.

**Comment by bryanray** [comment]
I see :)) LOL
