### ISSUE TITLE
Adapt Gradio 3.22

### ISSUE THREAD

**Issue by Sakura-Luna** [AlUlkesh/stable-diffusion-webui-images-browser#96]
WebUI is trying to migrate to Gradio 3.22/23, but this extension will prevent the loading of the web, see the details in https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/8752

**Comment by AlUlkesh** [comment]
Thanks for bringing this to my attention! I'll look into it.

Having the latest Gradio version sure would have saved me a lot of headache with my latest changes...
