### ISSUE TITLE
Extension fails to load

### ISSUE THREAD

**Issue by BanditSan** [AlUlkesh/stable-diffusion-webui-images-browser#97]
Extensions fails to load with error:

> Error loading script: image_browser.py
Traceback (most recent call last):
  File "/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser/scripts/image_browser.py", line 25, in <module>
    from scripts.wib import wib_db
ModuleNotFoundError: No module named 'scripts.wib'

Running latest WebUI with [Arch-specific dependencies](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs#arch-specific-dependencies)

**Comment by AlUlkesh** [comment]
Please post the **complete** console log, starting with:
```
z:\AI\stable-diffusion-webui_current>webui-user.bat
venv "z:\AI\stable-diffusion-webui_current\venv\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: 41e24e21164e68979c40c7e02a828780c8c4dc0c
```

**Comment by AlUlkesh** [comment]
Thanks. Nothing odd as far as I can tell. Let's look again at the error message:

```
  File "/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser/scripts/image_browser.py", line 25, in <module>
    from scripts.wib import wib_db
ModuleNotFoundError: No module named 'scripts.wib'
```

Can it just not find the file or is actually not there? Can you check if you have a file `scripts/wib/wib_db.py` in the extension's directory?

**Comment by BanditSan** [comment]
All file are in place:
```
$ ls extensions/stable-diffusion-webui-images-browser/scripts/
__pycache__  image_browser.py  wib

$ ls extensions/stable-diffusion-webui-images-browser/scripts/wib/
wib_db.py
```

**Comment by AlUlkesh** [comment]
I tried several things and installs, but I wasn't able to reproduce this error.

I wonder if it is a problem with your python? Do other extensions work, that use sub-directories, for example
https://github.com/fkunn1326/openpose-editor ?

**Comment by BanditSan** [comment]
During weekend tested SD-webui on fresh archlinux in VM and docker. Extensions is running fine one fresh installs.
On my main systems there is something messed up with python cache or etc. Few other extensions spiting this error. Interesting that non of system application having this problem, only sd-webui extensions in virtualenv.

P.S.
Alt import method works on my "broken" system

**Comment by AlUlkesh** [comment]
That is odd. Well, whatever, good to hear you got it working.

**Comment by BanditSan** [comment]
> That is odd. Well, whatever, good to hear you got it working.

To be fair nothing odd since this system was installed 8-9 years ago and survived multiple storage migrations an hardware upgrades. I just need to find some left over old trash or some old environment variable that is causing this issue.

**Comment by ZeldaMaster501** [comment]
I am currently away from my main pc for a few days, but I just realized something.  I was doing some reconfiguring, mainly stopping conda from auto-activating its base environment.  I didnt realize at the time but the errors for the other extensions vanished (and yes I launched AUTO1111's SD with and without conda's base environment being activated.  Maybe it has to do with how conda handles paths?  I seem to recall echoing $PATH before and after disabling the auto-activation and the path remained pointed to the conda install...  I'll have to explore further when I get back, but for now if someone could experiment, I'd appreciate it.

It'd be interesting to see if @BanditSan is running conda at all.

**Comment by BanditSan** [comment]
> It'd be interesting to see if @BanditSan is running conda at all.

Simple answer is no. I might have experimented with anaconda automation stuff in the past but usually i do such experimentation in VM not on my main system.

Since im not a developer and don't need any fancy stuff for personal use i run python scripts with system packages. Or when i need some modules that are not available in official Arch repo or AUR i just run vanilla python virtualenv.
My SD is installed just like described in [Arch-specific dependencies](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs#arch-specific-dependencies)
